const test=require('node:test');
const assert=require('node:assert/strict');
const E=require('./bakumatsu-character-engine.js');
const D=require('./bakumatsu-character-data.js');
const run=(s,c,rng=()=>.99)=>{const r=E.act(s,c,rng);assert.equal(r.ok,true,r.message);return r;};
const sustain=s=>{const p=E.active(s);if(p.hp<25){while(p.money<15)run(s,{type:'work'});run(s,{type:'rest'});run(s,{type:'rest'});}};
function persuade(s,id){let count=0;while(s.peopleById[id].ideology!==E.active(s).ideology || E.relationship(s,s.activePersonId,id)<80){sustain(s);run(s,{type:'persuade',target:id,method:'本音',spirit:1});assert.ok(++count<30);}}
function unify(s){for(const d of D.domains){const to=D.capitals[d.id]||d.id;if(to!==E.active(s).locationId)run(s,{type:'move',to,method:'walk'});for(const rank of [1,2,3])persuade(s,`${d.id}-${rank}`);}assert.equal(E.unified(s),11);}
test('respect: no loss of time or resources for unavailable audience / insufficient resources',()=>{const s=E.create('ansei','ryoma'),before=JSON.stringify(s);assert.equal(E.act(s,{type:'audience',with:'emperor'}).ok,false);assert.equal(JSON.stringify(s),before);s.peopleById.ryoma.money=0;const b=JSON.stringify(s);assert.equal(E.act(s,{type:'train',skill:'sword'}).ok,false);assert.equal(JSON.stringify(s),b);run(s,{type:'work'});assert.equal(E.active(s).money,25);});
test('introductions, trust 79/80 and switch maintain separate money and locations',()=>{const s=E.create('bunkyu','ryoma');assert.equal(E.canMeet(s,s.peopleById['tosa-2']).ok,false);s.peopleById['tosa-1'].ideology='尊王';s.relationships['ryoma:tosa-1']=79;assert.equal(E.canMeet(s,s.peopleById['tosa-2']).ok,false);run(s,{type:'persuade',target:'tosa-1',method:'本音',spirit:.5});assert.ok(E.canMeet(s,s.peopleById['tosa-2']).ok);persuade(s,'tosa-2');assert.ok(E.canMeet(s,s.peopleById['tosa-3']).ok);const heroMoney=s.peopleById.ryoma.money;run(s,{type:'switch',target:'tosa-2'});run(s,{type:'work'});assert.equal(s.peopleById.ryoma.money,heroMoney);run(s,{type:'switch',target:'ryoma'});assert.equal(s.activePersonId,'ryoma');});
test('4 phases / Gregorian leap and year boundary / deadline cannot be bypassed',()=>{const s=E.create('ansei','katsu');for(let i=0;i<4;i++)run(s,{type:'wait'});assert.deepEqual(s.date,{year:1858,month:6,day:2,phase:0});s.date={year:1860,month:2,day:28,phase:3};run(s,{type:'wait'});assert.equal(s.date.day,29);s.date={year:1860,month:2,day:29,phase:3};run(s,{type:'wait'});assert.equal(s.date.month,3);s.date={year:1868,month:12,day:31,phase:3};for(const d of Object.values(s.domainsById))d.ideology='公議';s.audiences.emperor=true;s.peopleById.katsu.locationId='edo';run(s,{type:'audience',with:'shogun'});assert.equal(s.status,'lost');const b=JSON.stringify(s);assert.equal(E.act(s,{type:'wait'}).ok,false);assert.equal(JSON.stringify(s),b);});
test('national and foreign thought are independent; conversion explicitly ends protagonist run',()=>{const s=E.create('ansei','katsu');s.peopleById['bakufu-1'].foreignPolicy='攘夷';s.peopleById['bakufu-1'].resistance=3;run(s,{type:'persuade',target:'bakufu-1',method:'理論',topic:'foreignPolicy'});assert.equal(s.peopleById['bakufu-1'].foreignPolicy,'開国');assert.equal(s.peopleById['bakufu-1'].ideology,'佐幕');const b=JSON.stringify(s);assert.equal(E.act(s,{type:'lecture',ideology:'尊王'}).ok,false);assert.equal(JSON.stringify(s),b);run(s,{type:'lecture',ideology:'尊王',confirmed:true});assert.equal(s.status,'lost');assert.deepEqual(E.validate(s),s);});
for(const [hero,ideology] of [['ryoma','尊王'],['katsu','公議'],['oguri','佐幕']])test(`complete playable path: ${ideology}`,()=>{const s=E.create('bunkyu',hero,'easy');unify(s);assert.equal(s.status,'playing');assert.ok(E.requirements(s).some(r=>!r.ok));if(ideology!=='公議'){const source='fukui';while(E.active(s).money<600)run(s,{type:'work'});for(let n=0;n<6;n++)run(s,{type:'policy',policy:'recruit'});run(s,{type:'campaign',source,target:ideology==='尊王'?'aizu':'choshu'});assert.equal(s.campaigns[ideology==='尊王'?'aizu':'choshu'],true);assert.equal(s.status,'playing');}if(ideology!=='尊王'){run(s,{type:'move',to:'kyoto',method:'walk'});run(s,{type:'audience',with:'emperor'});}if(ideology!=='佐幕'){run(s,{type:'move',to:'edo',method:'walk'});run(s,{type:'audience',with:'shogun'});}assert.equal(s.status,'won');assert.ok(s.date.year<1869);assert.deepEqual(E.validate(s),s);console.log(`${ideology} achieved on ${E.dateLabel(s)}`);});
test('duel success, flee and protagonist death enforce end of story',()=>{const s=E.create('ansei','katsu');run(s,{type:'persuade',target:'bakufu-1',method:'脅迫'},()=>0);assert.ok(s.duel);assert.equal(E.act(s,{type:'wait'}).ok,false);run(s,{type:'flee'});assert.equal(s.duel,null);s.duel={targetId:'bakufu-1',enemyHp:70,stance:0,round:0};s.peopleById.katsu.hp=1;run(s,{type:'strike',strike:1});assert.equal(s.status,'lost');assert.equal(s.peopleById.katsu.alive,false);assert.deepEqual(E.validate(s),s);});
test('counter persuasion: safe departure and failure/defection',()=>{const s=E.create('ansei','katsu');run(s,{type:'persuade',target:'bakufu-1',method:'理論'},()=>0);assert.ok(s.pendingCounter);run(s,{type:'counter',response:'leave'});assert.equal(s.peopleById.katsu.resistance,100);s.pendingCounter='bakufu-1';s.peopleById.katsu.learning=0;s.peopleById.katsu.charm=0;s.peopleById.katsu.resistance=30;run(s,{type:'counter',response:'argue'},()=>0);assert.equal(s.status,'lost');});
test('save roundtrip and rejection of wrong/missing/referenced/injected state',()=>{const s=E.create('ansei','saigo');run(s,{type:'work'});assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);for(const mutate of [x=>x.schemaVersion=99,x=>x.date.day=32,x=>x.peopleById.saigo.money=-1,x=>x.activePersonId='not-a-person',x=>x.domainsById.saga.leaderId='ryoma',x=>x.peopleById.saigo.learning='90',x=>x.relationships['__proto__:saigo']=80,x=>x.pendingCounter='nobody',x=>x.settings.timer='yes',x=>x.status='won']){const bad=JSON.parse(JSON.stringify(s));mutate(bad);assert.throws(()=>E.validate(bad));}});
test('recruited leader can exercise own government after switching',()=>{const s=E.create('ansei','katsu');for(const rank of [2,3])persuade(s,`bakufu-${rank}`);run(s,{type:'switch',target:'bakufu-3'});assert.ok(E.authority(s,'bakufu'));const n=s.domainsById.bakufu.troops;run(s,{type:'policy',policy:'recruit'});assert.equal(s.domainsById.bakufu.troops,n+800);});
test('all five methods consume expected resources and respond to relevant ability',()=>{for(const method of D.methods){const low=E.create('ansei','ryoma','easy'),high=E.create('ansei','ryoma','easy');const target='tosa-1';low.peopleById[target].ideology='尊王';high.peopleById[target].ideology='尊王';for(const s of [low,high])s.peopleById.ryoma.money=20;if(method==='理論')high.peopleById.ryoma.learning=100,low.peopleById.ryoma.learning=0;if(method==='本音')high.peopleById.ryoma.charm=100,low.peopleById.ryoma.charm=0;if(method==='脅迫')high.peopleById.ryoma.sword=100,high.peopleById.ryoma.military=100,low.peopleById.ryoma.sword=0,low.peopleById.ryoma.military=0;if(method==='賄賂')high.peopleById.ryoma.money=200;if(method==='威圧'){for(const rank of [0,1,2]){high.peopleById[`tosa-${rank}`].ideology='尊王';high.relationships[`ryoma:tosa-${rank}`]=80;}}
 const beforeLow=E.relationship(low,'ryoma',target),beforeHigh=E.relationship(high,'ryoma',target);run(low,{type:'persuade',target,method,spirit:.5});run(high,{type:'persuade',target,method,spirit:.5});assert.ok(E.relationship(high,'ryoma',target)-beforeHigh>E.relationship(low,'ryoma',target)-beforeLow);assert.equal(low.peopleById.ryoma.money,method==='賄賂'?0:20);assert.equal(low.peopleById.ryoma.hp,method==='賄賂'?100:95);}});

