const test=require('node:test'),a=require('node:assert/strict'),B=require('./bakumatsu-battle.js'),E=require('./bakumatsu-character-engine.js');
const run=(s,c)=>{const r=E.act(s,c,()=>.5);a.equal(r.ok,true,r.message);return r};
test('19 distinct events: participants, staging, flags, dates, once-only',()=>{a.equal(B.events.length,19);a.equal(new Set(B.events.map(e=>e.id)).size,19);for(const e of B.events){const s=E.create('history1863','saigo');E.active(s).domainId=e.sides[0][0];E.active(s).locationId=e.location;const [year,month,day]=e.date.split('-').map(Number);s.date={year,month,day,phase:0};s.history.mobilized=true;s.history.causes[e.cause]=true;if(e.id==='ooda')s.history.results.kozanji='victory';a.equal(B.conditions(s,e).checks.every(c=>c.ok),true,e.id);B.trigger(s);a.equal(s.battle.eventId,e.id,e.id);s.battle=null;s.history.results[e.id]='victory';a.equal(B.conditions(s,e).checks.every(c=>c.ok),false);}});
test('orders, river barriers, AP, defense, AI, retreat, saves',()=>{const s=E.create('ansei','saigo');run(s,{type:'battlePractice',event:'toba'});run(s,{type:'battleBegin'});const b=s.battle,u=b.units[0];a.equal(B.reachable(b,u,4,1),false);run(s,{type:'battleOrder',unit:u.id,order:'move',x:2,y:1});run(s,{type:'battleOrder',unit:u.id,order:'defend'});a.equal(u.ap,0);const before=JSON.stringify(s);a.equal(E.act(s,{type:'battleOrder',unit:u.id,order:'move',x:3,y:1}).ok,false);a.equal(JSON.stringify(s),before);a.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);run(s,{type:'battleEndTurn'});a.equal(u.ap,2);run(s,{type:'battleRetreat'});a.equal(b.outcome,'retreat');const troops=s.domainsById.satsuma.troops;run(s,{type:'battleFinish'});a.equal(s.domainsById.satsuma.troops,troops);a.equal(s.battle,null);});
test('First expedition offers historical negotiated settlement',()=>{const s=E.create('ansei','saigo');run(s,{type:'battlePractice',event:'first-choshu'});a.equal(s.battle.phase,'negotiation');run(s,{type:'battlePeace'});a.equal(s.battle.outcome,'peace');run(s,{type:'battleFinish'});});
test('invalid units, overlap and conflicting battles rejected',()=>{const s=E.create('ansei','saigo');run(s,{type:'battlePractice',event:'hakodate'});for(const mutate of [x=>x.battle.units[0].x=20,x=>x.battle.units[0].name={},x=>x.battle.practice='yes',x=>{x.battle.units[1].x=1;x.battle.units[1].y=1},x=>x.history=null]){const c=structuredClone(s);mutate(c);a.throws(()=>E.validate(c));}});
test('Hakodate is playable in 1869 and waiting starts Satsuei',()=>{const s=E.create('history1863','saigo');run(s,{type:'historySettings',enabled:true,mobilized:true,causes:{foreign:true,choshu:false,boshin:false,reform:false}});run(s,{type:'historyWait'});a.equal(s.battle.eventId,'satuei');a.equal(s.date.day,15);const t=E.create('boshin','oguri');t.date={year:1869,month:6,day:20,phase:0};a.deepEqual(E.validate(t),t);});


test('small army deployment does not create additional troops',()=>{const b=B.create({name:'test',troops:400,date:'1863-08-01'});a.ok(b.units.filter(u=>u.team==='player').reduce((sum,u)=>sum+u.hp,0)<=400);});
