(function(root){
 'use strict';
 const event=(id,name,date,end,place,location,sides,cause,terrain,source,note='')=>({id,name,date,end,place,location,sides,cause,terrain,source,note});
 const events=[
 event('satuei','薩英戦争','1863-08-15','1863-08-31','鹿児島湾・鹿児島城下','satsuma',[['satsuma'],[]],'foreign','coast','https://www.mofa.go.jp/mofaj/files/000179293.pdf','生麦事件の賠償・犯人処罰交渉の決裂。相手は英国艦隊。'),
 event('kinmon','禁門の変（蛤御門の変）','1864-08-20','1864-08-31','京都御所・蛤御門周辺','kyoto',[['choshu'],['aizu','satsuma','kuwana','bakufu']],'choshu','town','https://www.city.kyoto.lg.jp/kamigyo/page/0000012502.html','長州勢の入京・復権要求と御所守備側の対立。'),
 event('first-choshu','第一次長州征討','1864-08-24','1865-01-24','長州境・広島の征長軍本営','choshu',[['choshu'],['bakufu','satsuma','fukui']],'choshu','fort','https://www.jacar.go.jp/learning/history.html','禁門の変後の追討。史実では服罪・交渉で本格戦闘を回避。開戦は仮想分岐。'),
 event('shimonoseki','下関戦争（四国艦隊砲撃）','1864-09-05','1864-09-30','下関・前田台場と関門海峡','choshu',[['choshu'],[]],'foreign','coast','https://www.jacar.go.jp/learning/term.html?uid=Y10C200010','前年の外国船砲撃に対する英仏蘭米艦隊の攻撃を扱う。'),
 event('kozanji','功山寺挙兵','1865-01-12','1865-01-31','下関市長府・功山寺','choshu',[['choshu'],[]],'reform','town','https://www.mlit.go.jp/tagengo-db/common/001781682.pdf','高杉晋作ら諸隊と藩内保守派。ゲームでは所属長州を諸隊側とする。'),
 event('ooda','大田・絵堂の戦い','1865-02-01','1865-02-28','美祢市美東町・大田と絵堂','choshu',[['choshu'],[]],'reform','hill','https://www.city.hagi.lg.jp/uploaded/attachment/11344.pdf','旧暦元治2年正月6日夜半～16日。功山寺挙兵に続く藩内戦。新暦では2月。'),
 event('second-choshu','第二次長州征討（四境戦争）','1866-07-18','1866-10-08','大島口・芸州口・石州口・小倉口','choshu',[['choshu'],['bakufu']],'choshu','coast','https://www.jacar.go.jp/learning/history.html','幕府の再征。薩摩は出兵拒否のため征討側に含めない。'),
 event('toba','鳥羽・伏見の戦い','1868-01-27','1868-01-31','京都・鳥羽街道と伏見','kyoto',[['satsuma','choshu'],['bakufu','aizu','kuwana']],'boshin','town','https://ja.kyoto.travel/tourism/single02.php?category_id=9&tourism_id=408','王政復古後、旧幕府軍の上京と薩長側の阻止。'),
 event('katsunuma','甲州勝沼の戦い','1868-03-29','1868-03-31','甲州市勝沼町・柏尾坂','edo',[['tosa','satsuma'],['bakufu']],'boshin','hill','https://www.city.koshu.yamanashi.jp/docs/2022112900021/','板垣退助ら東山道軍と近藤勇ら甲陽鎮撫隊。ゲーム上の集結拠点は江戸。'),
 event('utsunomiya','宇都宮城の戦い','1868-05-11','1868-05-15','宇都宮城と城下','mito',[['satsuma','tosa'],['bakufu','aizu']],'boshin','fort','https://utsunomiya-8story.jp/search_post/戊辰戦争宇都宮城攻防図/','旧暦4月19日・23日の攻防。集結拠点は水戸。'),
 event('funabashi','市川・船橋の戦い','1868-05-24','1868-05-31','市川・船橋・鎌ヶ谷','edo',[['satsuma'],['bakufu']],'boshin','town','https://www.lib.city.funabashi.lg.jp/viewer/info.html?g=23&id=79&idSubTop=2','旧暦閏4月3日。旧幕府撒兵隊と岡山・津・福岡・佐土原、薩摩等。'),
 event('shirakawa','白河口の戦い','1868-06-10','1868-09-14','白河小峰城と周辺','tohoku',[['satsuma','choshu','tosa'],['aizu','bakufu']],'boshin','fort','https://www.city.shirakawa.fukushima.jp/data/doc/1776929234_doc_71_0.pdf','旧暦閏4月20日からの攻防。史料の「4月20日」は閏月に注意。'),
 event('ueno','彰義隊の戦い／上野戦争','1868-07-04','1868-07-31','江戸・上野寛永寺周辺','edo',[['satsuma','choshu','tosa'],['bakufu']],'boshin','town','https://www.culture.city.taito.lg.jp/bunkatanbou/history/kiyomizu_kannondo/japanese/page_02.html','新政府軍と上野に集結した彰義隊。'),
 event('akita','秋田戦争','1868-08-28','1868-11-01','秋田県域・出羽北部','shonai',[['satsuma','choshu','tosa'],['shonai','bakufu']],'boshin','hill','https://www.city.daisen.lg.jp/uploads/contents/archive_0000001384_00/siryou01.pdf','秋田藩の同盟離脱後、庄内・仙台・南部等と新政府・秋田側の戦闘。集結拠点は鶴岡。'),
 event('hatcho','北越戦争（八丁沖の戦い）','1868-09-11','1868-09-30','長岡・八丁沖と長岡城','nagaoka',[['nagaoka','aizu'],['satsuma','choshu']],'boshin','marsh','https://www.pref.niigata.lg.jp/sec/nagaoka_kikaku/1356899128031.html','旧暦7月24日夜の渡河～25日（新暦9月11日）の攻撃。'),
 event('nihonmatsu','二本松の戦い','1868-09-15','1868-09-30','二本松城・城下','tohoku',[['satsuma','choshu','tosa'],['aizu','bakufu']],'boshin','fort','https://www.city.shirakawa.fukushima.jp/data/doc/1776929234_doc_71_0.pdf','二本松藩と新政府軍。未収録藩の参加は会津側の同盟派遣として抽象化。'),
 event('bonari','母成峠の戦い','1868-10-06','1868-10-07','母成峠（郡山・猪苗代境）','tohoku',[['satsuma','tosa'],['bakufu','aizu']],'boshin','hill','https://www.city.shirakawa.fukushima.jp/data/doc/1776929234_doc_71_0.pdf','旧暦8月21日。大鳥圭介ら旧幕府側の峠防衛。'),
 event('aizu-war','会津戦争','1868-10-08','1868-11-06','会津若松城と会津盆地','tohoku',[['satsuma','choshu','tosa'],['aizu','bakufu','kuwana']],'boshin','fort','https://www.city.shirakawa.fukushima.jp/data/doc/1776929234_doc_71_0.pdf','旧暦8月23日～9月22日の籠城戦を中心に扱う。'),
 event('hakodate','箱館戦争（五稜郭の戦い）','1868-12-04','1869-06-27','箱館・五稜郭と道南','ezo',[['satsuma','choshu','tosa'],['bakufu','kuwana']],'boshin','fort','https://hakodate-bugyosho.jp/history/hakodate-war/','箱館戦争全体は1868年12月～1869年6月。旧暦5月11日の総攻撃は新暦6月20日。')
 ];
 const stamp=d=>`${d.year}-${String(d.month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`;
 const causes={foreign:'対外交渉決裂',choshu:'長州と幕府・朝廷の対立',boshin:'新政府と旧幕府の武力対立',reform:'長州藩内の改革派挙兵'};
 function init(s,enabled=false){s.history={enabled,mobilized:false,causes:{foreign:false,choshu:false,boshin:false,reform:false},results:{}};s.battle=null;}
 function conditions(s,e){const p=s.peopleById[s.activePersonId],day=stamp(s.date),side=e.sides.findIndex(ids=>ids.includes(p.domainId));return {side,checks:[{label:`期間 ${e.date}～${e.end}（新暦）`,ok:day>=e.date&&day<=e.end},{label:`当事者：参加藩・同盟派遣（${p.domainId}）`,ok:side>=0},{label:`集結拠点：${e.location}`,ok:p.locationId===e.location},{label:'参陣を志願',ok:s.history.mobilized},{label:causes[e.cause],ok:!!s.history.causes[e.cause]},{label:'所属藩の兵400以上',ok:(s.domainsById[p.domainId]?.troops||0)>=400},{label:'未決着',ok:!s.history.results[e.id]},{label:'功山寺挙兵の決着',ok:e.id!=='ooda'||!!s.history.results.kozanji}]};}
 function trigger(s){if(!s.history?.enabled||s.status!=='playing'||s.battle||s.duel||s.pendingCounter)return;const e=events.find(e=>conditions(s,e).checks.every(c=>c.ok));if(e){const p=s.peopleById[s.activePersonId];s.battle=create({name:e.name,eventId:e.id,source:p.domainId,side:conditions(s,e).side,terrain:e.terrain,troops:s.domainsById[p.domainId].troops,training:s.domainsById[p.domainId].training,modernization:s.domainsById[p.domainId].modernization,phase:e.id==='first-choshu'?'negotiation':'briefing',date:stamp(s.date)});}}
 function terrainAt(theme,x,y){if(theme==='coast'&&x>=7)return 'water';if(theme==='marsh'&&x===4&&y!==3)return 'marsh';if(x===4&&y!==3)return 'river';if((x===2||x===6)&&(y===1||y===4))return 'forest';if(theme==='hill'&&(x===5||x===6)&&y===2)return 'hill';if(theme==='town'&&(x===2||x===6)&&y!==3)return 'town';if(theme==='fort'&&x===7&&y>=1&&y<=4)return 'fort';return 'plain';}
 function create(o){const b={version:1,name:o.name,eventId:o.eventId||null,source:o.source||null,target:o.target||null,side:o.side||0,terrain:o.terrain||'hill',phase:o.phase||'briefing',turn:1,outcome:null,date:o.date||'',practice:!!o.practice,log:['部隊を選び、移動・攻撃・防御を指示してください。'],units:[],initialTroops:o.troops||2400};const total=Math.min(3600,Math.max(600,o.troops||2400)),power=12+Math.round((o.training||35)/10)+Math.round((o.modernization||0)/20),enemy=Math.max(900,Math.min(3500,o.enemyTroops||total));for(const team of ['player','enemy'])for(let i=0;i<3;i++){const ship=team==='enemy'&&b.terrain==='coast',kind=ship?'ship':i===2?'cannon':'infantry';b.units.push({id:team+'-'+i,team,kind,name:(team==='player'?'味方':'敵')+['第一隊','第二隊','砲兵隊'][i],x:team==='player'?1:ship?8:7,y:[1,3,4][i],hp:Math.round((team==='player'?total:enemy)/3),maxHp:Math.round((team==='player'?total:enemy)/3),morale:100,attack:(team==='player'?power:16+Math.round((o.enemyTraining||35)/20))+(i===2?8:0),range:kind==='infantry'?2:4,ap:2,guard:false});}return b;}
 const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
 function reachable(b,u,x,y){if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||x>8||y<0||y>5)return false;if(b.units.some(v=>v.hp>0&&v.id!==u.id&&v.x===x&&v.y===y))return false;const tile=terrainAt(b.terrain,x,y);if(u.kind==='ship'?tile!=='water':tile==='water'||tile==='river')return false;const limit=u.kind==='cannon'?1:2;const queue=[[u.x,u.y,0]],seen=new Set([u.x+','+u.y]);while(queue.length){const [a,c,n]=queue.shift();if(a===x&&c===y)return n>0;if(n===limit)continue;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=a+dx,ny=c+dy,key=nx+','+ny,t=terrainAt(b.terrain,nx,ny);if(nx<0||nx>8||ny<0||ny>5||seen.has(key)||(u.kind==='ship'?t!=='water':['water','river'].includes(t))||b.units.some(v=>v.hp>0&&v.id!==u.id&&v.x===nx&&v.y===ny))continue;seen.add(key);queue.push([nx,ny,n+1]);}}return false;}
 function damage(b,u,v,rng){const cover=({forest:.75,town:.8,hill:.85,fort:.65,marsh:1.15})[terrainAt(b.terrain,v.x,v.y)]||1;const amount=Math.max(35,Math.round((u.attack*7+u.hp*.025)*(v.guard?.5:1)*cover*(.9+rng()*.2)*(u.morale/100)));v.hp=Math.max(0,v.hp-amount);v.morale=Math.max(0,v.morale-12);if(v.morale===0)v.hp=0;b.log.unshift(`${u.name}の攻撃：${v.name}に${amount}損害。`);return amount;}
 function conclude(b){if(!b.units.some(u=>u.team==='player'&&u.hp>0))b.outcome='defeat';else if(!b.units.some(u=>u.team==='enemy'&&u.hp>0))b.outcome='victory';if(b.outcome)b.phase='result';b.log=b.log.slice(0,12);}
 function act(b,c,rng=Math.random){if(!b)return {ok:false,message:'合戦は発生していません。'};if(c.type==='battleBegin'&&['briefing','negotiation'].includes(b.phase)){b.phase='fighting';return {ok:true,message:'合戦開始。'};}if(c.type==='battlePeace'&&b.phase==='negotiation'){b.outcome='peace';b.phase='result';return {ok:true,message:'交渉により撤兵。史実同様、戦闘を回避した。'};}if(b.phase!=='fighting')return {ok:false,message:'合戦の開始・結果確認を行ってください。'};if(c.type==='battleRetreat'){b.outcome='retreat';b.phase='result';return {ok:true,message:'全軍撤退。生き残った兵を帰還させる。'};}if(c.type==='battleOrder'){const u=b.units.find(u=>u.id===c.unit&&u.team==='player'&&u.hp>0);if(!u||u.ap<1)return {ok:false,message:'行動できる味方部隊を選んでください。'};if(c.order==='move'){if(!reachable(b,u,c.x,c.y))return {ok:false,message:'移動範囲・地形・部隊の重なりを確認してください。'};u.x=c.x;u.y=c.y;u.guard=false;}else if(c.order==='attack'){const v=b.units.find(v=>v.id===c.target&&v.team==='enemy'&&v.hp>0);if(!v||dist(u,v)>u.range)return {ok:false,message:'射程内の敵部隊を選んでください。'};damage(b,u,v,rng);u.guard=false;}else if(c.order==='defend'){u.guard=true;u.morale=Math.min(100,u.morale+8);u.ap=1;b.log.unshift(`${u.name}が防御。次の敵攻撃の損害を半減。`);}else return {ok:false,message:'命令が不正です。'};u.ap--;conclude(b);return {ok:true,message:b.log[0]||'移動した。'};}
 if(c.type==='battleEndTurn'){for(const u of b.units.filter(u=>u.team==='enemy'&&u.hp>0)){let targets=b.units.filter(v=>v.team==='player'&&v.hp>0).sort((a,v)=>dist(u,a)-dist(u,v));let target=targets[0];if(!target)break;u.guard=false;if(dist(u,target)>u.range){const options=[];for(let x=0;x<9;x++)for(let y=0;y<6;y++)if(reachable(b,u,x,y))options.push({x,y});options.sort((a,v)=>dist(a,target)-dist(v,target));if(options[0]){u.x=options[0].x;u.y=options[0].y;}}if(dist(u,target)<=u.range)damage(b,u,target,rng);else u.guard=true;conclude(b);if(b.outcome)break;}b.turn++;if(b.turn>40&&!b.outcome){b.outcome='retreat';b.phase='result';b.log.unshift('長期戦で兵糧が尽き、撤退した。');}for(const u of b.units.filter(u=>u.team==='player')){u.ap=2;u.guard=false;}conclude(b);return {ok:true,message:`第${b.turn}ターン。敵軍が行動した。`};}return {ok:false,message:'合戦命令が不正です。'};}
 function validate(s){if(!s.history){if(s.battle)throw Error('歴史設定のない合戦記録です。');init(s,false);}const h=s.history;if(typeof h.enabled!=='boolean'||typeof h.mobilized!=='boolean'||!h.causes||!h.results||Array.isArray(h.results))throw Error('歴史イベント記録が不正です。');for(const key of Object.keys(causes))if(typeof h.causes[key]!=='boolean')throw Error('イベント契機が不正です。');for(const [key,v] of Object.entries(h.results))if(!events.some(e=>e.id===key)||!['victory','defeat','retreat','peace'].includes(v))throw Error('歴史結果が不正です。');h.causes=Object.fromEntries(Object.keys(causes).map(k=>[k,h.causes[k]]));if(s.battle){const b=s.battle,numeric=(v,lo,hi)=>Number.isInteger(v)&&v>=lo&&v<=hi;if(typeof b.practice!=='boolean'||![0,1].includes(b.side)||typeof b.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||b.version!==1||!['briefing','negotiation','fighting','result'].includes(b.phase)||!['hill','fort','town','marsh','coast'].includes(b.terrain)||!numeric(b.turn,1,41)||!Array.isArray(b.units)||b.units.length!==6||b.units.some((u,i)=>typeof u.name!=='string'||u.name.length>120||u.id!==['player','enemy'][Math.floor(i/3)]+'-'+i%3||u.team!==['player','enemy'][Math.floor(i/3)]||!['infantry','cannon','ship'].includes(u.kind)||!numeric(u.x,0,8)||!numeric(u.y,0,5)||!numeric(u.hp,0,1200)||!numeric(u.maxHp,200,1200)||u.hp>u.maxHp||!numeric(u.ap,0,2)||!numeric(u.morale,0,100)||!numeric(u.attack,1,50)||!numeric(u.range,1,4)||typeof u.guard!=='boolean')||!Array.isArray(b.log)||b.log.length>12||b.log.some(x=>typeof x!=='string'||x.length>300)||!numeric(b.initialTroops,400,99999)||b.eventId&&!events.some(e=>e.id===b.eventId)||b.source&&!s.domainsById[b.source]||b.target&&!s.domainsById[b.target]||!['victory','defeat','retreat','peace',null].includes(b.outcome)||!['string'].includes(typeof b.name)||b.name.length>120||(b.phase==='result')!==!!b.outcome)throw Error('合戦記録が不正です。');if(b.outcome==='victory'&&b.units.some(u=>u.team==='enemy'&&u.hp>0)||b.outcome==='defeat'&&b.units.some(u=>u.team==='player'&&u.hp>0))throw Error('勝敗と部隊の状態が一致しません。');if(s.duel||s.pendingCounter)throw Error('戦闘状態が競合しています。');const alive=b.units.filter(u=>u.hp>0);if(new Set(alive.map(u=>u.x+','+u.y)).size!==alive.length)throw Error('部隊が重複しています。');}}
 const api={events,causes,init,conditions,trigger,create,terrainAt,reachable,act,validate,stamp};root.BakumatsuBattle=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
