const GAME_DATA = {
  start: { year: 1853, month: 7, treasury: 780, court: 48, modernization: 18, tension: 32 },
  factions: [
    { id: 'bakufu', name: '江戸幕府', color: '#a34b38', attitude: '佐幕・開国' },
    { id: 'satsuma', name: '薩摩藩', color: '#b78935', attitude: '雄藩・現実派' },
    { id: 'choshu', name: '長州藩', color: '#50705a', attitude: '攘夷・改革派' },
    { id: 'aizu', name: '会津藩', color: '#516886', attitude: '佐幕・京都守護' },
    { id: 'tosa', name: '土佐藩', color: '#6c5b8c', attitude: '公議政体派' }
  ],
  regions: [
    { id: 'ezo', name: '蝦夷地', x: 78, y: 9, faction: 'bakufu', kokudaka: '—', asset: '箱館港', note: '北方防備と海軍拠点。箱館奉行の統治下にある。' },
    { id: 'tohoku', name: '奥羽', x: 74, y: 31, faction: 'aizu', kokudaka: '会津 23万石', asset: '若松城', note: '奥羽諸藩は幕府との結び付きが強い。' },
    { id: 'echigo', name: '越後', x: 66, y: 41, faction: 'bakufu', kokudaka: '長岡 7万4千石', asset: '新潟港', note: '日本海の港と交通の要地。' },
    { id: 'edo', name: '関東・江戸', x: 71, y: 53, faction: 'bakufu', kokudaka: '幕府領', asset: '江戸城', note: '将軍家の本拠。全国政治の中心。' },
    { id: 'kyoto', name: '畿内・京都', x: 57, y: 56, faction: 'neutral', kokudaka: '朝廷領', asset: '京都御所', note: '勅許と朝廷工作が国家の正統性を左右する。' },
    { id: 'choshu', name: '長州', x: 39, y: 60, faction: 'choshu', kokudaka: '36万9千石', asset: '下関海峡', note: '西国の雄藩。海峡支配と軍制改革が鍵。' },
    { id: 'satsuma', name: '薩摩', x: 19, y: 78, faction: 'satsuma', kokudaka: '72万9千石', asset: '鹿児島城下', note: '豊かな財政と対外交易を持つ西南の大藩。' },
    { id: 'tosa', name: '土佐', x: 46, y: 72, faction: 'tosa', kokudaka: '24万2千石', asset: '高知城下', note: '海援隊をはじめとする人材が集う。' }
  ],
  people: [
    { id: 'tokugawa-yoshinobu', name: '徳川 慶喜', faction: '江戸幕府', role: '将軍後見職', stats: [74, 63, 46, 87], ideology: '佐幕 65 / 開国 72', trait: '政局眼・洋式軍制', portrait: 'assets/portraits/tokugawa-yoshinobu.png', tint: '#9b3e2f' },
    { id: 'saigo-takamori', name: '西郷 隆盛', faction: '薩摩藩', role: '薩摩藩士', stats: [91, 74, 83, 62], ideology: '倒幕 78 / 開国 56', trait: '人望・統率', portrait: 'assets/portraits/saigo-takamori.png', tint: '#b78b37' },
    { id: 'kido-takayoshi', name: '木戸 孝允', faction: '長州藩', role: '長州藩士', stats: [57, 65, 31, 91], ideology: '倒幕 86 / 開国 71', trait: '政治工作・蘭学', portrait: 'assets/portraits/kido-takayoshi.png', tint: '#4f6f58' },
    { id: 'sakamoto-ryoma', name: '坂本 龍馬', faction: '土佐藩', role: '土佐脱藩浪士', stats: [68, 61, 69, 83], ideology: '公議政体 / 開国 88', trait: '交渉・海軍', portrait: 'assets/portraits/sakamoto-ryoma.png', tint: '#69558c' },
    { id: 'matsudaira-katamori', name: '松平 容保', faction: '会津藩', role: '京都守護職', stats: [79, 68, 57, 66], ideology: '佐幕 91 / 攘夷 46', trait: '忠節・守城', portrait: 'assets/portraits/matsudaira-katamori.png', tint: '#4a6687' },
    { id: 'okubo-toshimichi', name: '大久保 利通', faction: '薩摩藩', role: '薩摩藩士', stats: [66, 58, 43, 93], ideology: '倒幕 75 / 開国 76', trait: '行政・改革', portrait: 'assets/portraits/okubo-toshimichi.png', tint: '#b78b37' },
    { id: 'ii-naosuke', name: '井伊 直弼', faction: '彦根藩・幕府', role: '大老', stats: [65, 55, 40, 94], ideology: '佐幕 86 / 開国 66', trait: '政局支配・決断', portrait: 'assets/portraits/ii-naosuke.png', tint: '#4a526c' },
    { id: 'katsu-kaishu', name: '勝 海舟', faction: '幕臣', role: '軍艦奉行並', stats: [69, 65, 41, 90], ideology: '公議政体 / 開国 94', trait: '海軍・外交', portrait: 'assets/portraits/katsu-kaishu.png', tint: '#356784' },
    { id: 'takasugi-shinsaku', name: '高杉 晋作', faction: '長州藩', role: '奇兵隊創設者', stats: [87, 88, 70, 71], ideology: '倒幕 91 / 開国 65', trait: '奇兵隊・機動戦', portrait: 'assets/portraits/takasugi-shinsaku.png', tint: '#4f6f58' },
    { id: 'hijikata-toshizo', name: '土方 歳三', faction: '新選組', role: '副長', stats: [84, 85, 76, 55], ideology: '佐幕 93 / 開国 44', trait: '軍律・突撃', portrait: 'assets/portraits/hijikata-toshizo.png', tint: '#415d87' },
    { id: 'enomoto-takeaki', name: '榎本 武揚', faction: '幕府海軍', role: '海軍副総裁', stats: [77, 79, 42, 84], ideology: '佐幕 82 / 開国 89', trait: '海軍・技術', portrait: 'assets/portraits/enomoto-takeaki.png', tint: '#356784' },
    { id: 'oomura-masujiro', name: '大村 益次郎', faction: '長州藩', role: '軍政家', stats: [72, 96, 31, 86], ideology: '倒幕 89 / 開国 83', trait: '軍略・近代軍制', portrait: 'assets/portraits/oomura-masujiro.png', tint: '#4f6f58' },
    { id: 'shimazu-nariakira', name: '島津 斉彬', faction: '薩摩藩', role: '藩主', stats: [72, 60, 39, 95], ideology: '雄藩 / 開国 86', trait: '近代化・人材登用', portrait: 'assets/portraits/shimazu-nariakira.png', tint: '#b78b37' },
    { id: 'komatsu-tatewaki', name: '小松 帯刀', faction: '薩摩藩', role: '家老', stats: [73, 62, 51, 91], ideology: '倒幕 71 / 開国 81', trait: '政治・外交', portrait: 'assets/portraits/komatsu-tatewaki.png', tint: '#b78b37' },
    { id: 'ito-hirobumi', name: '伊藤 博文', faction: '長州藩', role: '長州藩士', stats: [63, 55, 38, 88], ideology: '倒幕 86 / 開国 87', trait: '政治工作・英学', portrait: 'assets/portraits/ito-hirobumi.png', tint: '#4f6f58' },
    { id: 'yamagata-aritomo', name: '山県 有朋', faction: '長州藩', role: '奇兵隊士', stats: [83, 90, 67, 72], ideology: '倒幕 85 / 開国 72', trait: '近代軍制・統率', portrait: 'assets/portraits/yamagata-aritomo.png', tint: '#4f6f58' },
    { id: 'kondo-isami', name: '近藤 勇', faction: '新選組', role: '局長', stats: [86, 79, 86, 48], ideology: '佐幕 94 / 攘夷 55', trait: '新選組・統率', portrait: 'assets/portraits/kondo-isami.png', tint: '#415d87' },
    { id: 'okita-soji', name: '沖田 総司', faction: '新選組', role: '一番隊組長', stats: [66, 83, 98, 37], ideology: '佐幕 88 / 攘夷 51', trait: '剣術・先制', portrait: 'assets/portraits/okita-soji.png', tint: '#415d87' },
    { id: 'takechi-hanpeita', name: '武市 半平太', faction: '土佐藩', role: '土佐勤王党首領', stats: [80, 71, 75, 83], ideology: '倒幕 78 / 攘夷 85', trait: '思想結集・統率', portrait: 'assets/portraits/takechi-hanpeita.png', tint: '#69558c' },
    { id: 'yamakawa-hiroshi', name: '山川 浩', faction: '会津藩', role: '家老', stats: [88, 80, 68, 64], ideology: '佐幕 91 / 攘夷 48', trait: '防衛戦・統率', portrait: 'assets/portraits/yamakawa-hiroshi.png', tint: '#4a6687' },
    { id: 'iwakura-tomomi', name: '岩倉 具視', faction: '朝廷', role: '公家', stats: [55, 48, 25, 96], ideology: '倒幕 78 / 開国 65', trait: '朝廷工作・謀略', portrait: 'assets/portraits/iwakura-tomomi.png', tint: '#7b6842' },
    { id: 'kawai-tsugunosuke', name: '河井 継之助', faction: '長岡藩', role: '家老', stats: [83, 88, 58, 86], ideology: '佐幕 61 / 開国 82', trait: 'ガトリング砲・軍略', portrait: 'assets/portraits/kawai-tsugunosuke.png', tint: '#9e633d' },
    { id: 'matsudaira-taro', name: '松平 太郎', faction: '蝦夷共和国', role: '陸軍奉行並', stats: [80, 82, 52, 74], ideology: '佐幕 88 / 開国 78', trait: '海軍・箱館政権', portrait: 'assets/portraits/matsudaira-taro.png', tint: '#356784' },
    { id: 'yamamoto-yaeko', name: '山本 八重', faction: '会津藩', role: '砲術家', stats: [69, 74, 78, 63], ideology: '佐幕 87 / 攘夷 43', trait: '砲術・士気', portrait: 'assets/portraits/yamamoto-yaeko.png', tint: '#4a6687' },
    { id: 'tokugawa-iemochi', name: '徳川 家茂', faction: '江戸幕府', role: '第14代将軍', stats: [51, 54, 35, 75], ideology: '佐幕 89 / 開国 54', trait: '人望・公武合体', portrait: 'assets/portraits/tokugawa-iemochi.png', tint: '#9b3e2f' },
    { id: 'matsudaira-shungaku', name: '松平 春嶽', faction: '福井藩', role: '藩主', stats: [64, 62, 42, 94], ideology: '公議政体 / 開国 78', trait: '政治・人材登用', portrait: 'assets/portraits/matsudaira-shungaku.png', tint: '#5d7088' },
    { id: 'shimazu-hisamitsu', name: '島津 久光', faction: '薩摩藩', role: '国父', stats: [67, 55, 45, 92], ideology: '雄藩 / 開国 62', trait: '政治・軍勢動員', portrait: 'assets/portraits/shimazu-hisamitsu.png', tint: '#b78b37' },
    { id: 'saito-hajime', name: '斎藤 一', faction: '新選組', role: '三番隊組長', stats: [63, 77, 96, 42], ideology: '佐幕 91 / 攘夷 57', trait: '剣術・偵察', portrait: 'assets/portraits/saito-hajime.png', tint: '#415d87' },
    { id: 'nagakura-shinpachi', name: '永倉 新八', faction: '新選組', role: '二番隊組長', stats: [73, 72, 94, 41], ideology: '佐幕 87 / 攘夷 54', trait: '剣術・突撃', portrait: 'assets/portraits/nagakura-shinpachi.png', tint: '#415d87' },
    { id: 'atsuhime', name: '篤姫（天璋院）', faction: '徳川家', role: '御台所', stats: [45, 42, 22, 90], ideology: '佐幕 88 / 開国 58', trait: '人脈・交渉・士気', portrait: 'assets/portraits/atsuhime.png', tint: '#9b3e2f' },
    { id: 'nabeshima-naomasa', name: '鍋島 直正', faction: '肥前佐賀藩', role: '藩主', stats: [67, 69, 35, 89], ideology: '雄藩 / 開国 91', trait: '技術力S・反射炉', portrait: 'assets/portraits/nabeshima-naomasa.png', tint: '#356d70' },
    { id: 'fujita-toko', name: '藤田 東湖', faction: '水戸藩', role: '水戸学者', stats: [58, 71, 42, 91], ideology: '尊攘 94 / 開国 24', trait: '思想・藩内派閥', portrait: 'assets/portraits/fujita-toko.png', tint: '#4a654d' },
    { id: 'yokoi-shonan', name: '横井 小楠', faction: '熊本藩・招聘', role: '政治顧問', stats: [47, 52, 19, 97], ideology: '公議政体 / 開国 93', trait: '改革・外交', portrait: 'assets/portraits/yokoi-shonan.png', tint: '#61734f' },
    { id: 'nakano-takeko', name: '中野 竹子', faction: '会津藩', role: '娘子隊', stats: [67, 74, 93, 56], ideology: '佐幕 92 / 攘夷 49', trait: '剣術・士気', portrait: 'assets/portraits/nakano-takeko.png', tint: '#4a6687' },
    { id: 'kazunomiya', name: '和宮親子内親王', faction: '朝廷・徳川家', role: '親王妃', stats: [38, 32, 18, 88], ideology: '公武合体 / 開国 56', trait: '朝廷・人脈', portrait: 'assets/portraits/kazunomiya.png', tint: '#786080' },
    { id: 'yamamoto-kakuma', name: '山本 覚馬', faction: '会津藩', role: '砲術家', stats: [61, 76, 35, 83], ideology: '佐幕 68 / 開国 78', trait: '砲術・技術', portrait: 'assets/portraits/yamamoto-kakuma.png', tint: '#4a6687' },
    { id: 'goto-shojiro', name: '後藤 象二郎', faction: '土佐藩', role: '藩士', stats: [68, 60, 42, 92], ideology: '公議政体 / 開国 86', trait: '政治・外交', portrait: 'assets/portraits/goto-shojiro.png', tint: '#69558c' },
    { id: 'itagaki-taisuke', name: '板垣 退助', faction: '土佐藩', role: '軍事指揮官', stats: [83, 79, 84, 65], ideology: '倒幕 83 / 開国 62', trait: '軍事・政治', portrait: 'assets/portraits/itagaki-taisuke.png', tint: '#69558c' },
    { id: 'mutsu-munemitsu', name: '陸奥 宗光', faction: '海援隊・土佐', role: '外交官', stats: [53, 48, 32, 96], ideology: '倒幕 79 / 開国 91', trait: '外交・交渉', portrait: 'assets/portraits/mutsu-munemitsu.png', tint: '#69558c' },
    { id: 'arai-ikunousuke', name: '荒井 郁之助', faction: '蝦夷共和国', role: '海軍奉行', stats: [77, 80, 45, 79], ideology: '佐幕 83 / 開国 88', trait: '海軍・技術', portrait: 'assets/portraits/arai-ikunousuke.png', tint: '#356784' },
    { id: 'jules-brunet', name: 'ジュール・ブリュネ', faction: '蝦夷共和国・フランス', role: '軍事顧問', stats: [84, 87, 72, 69], ideology: '旧幕府支援 / 開国 95', trait: '砲術・顧問', portrait: 'assets/portraits/jules-brunet.png', tint: '#356784' },
    { id: 'yoshida-shoin', name: '吉田 松陰', faction: '長州藩', role: '思想家', stats: [42, 46, 35, 94], ideology: '尊攘 97 / 開国 38', trait: '思想・教育', portrait: 'assets/portraits/yoshida-shoin.png', tint: '#4f6f58' },
    { id: 'oguri-tadamasa', name: '小栗 忠順', faction: '江戸幕府', role: '幕臣', stats: [71, 68, 36, 96], ideology: '佐幕 84 / 開国 82', trait: '政治・経済', portrait: 'assets/portraits/oguri-tadamasa.png', tint: '#9b3e2f' },
    { id: 'egawa-hidetatsu', name: '江川 英龍', faction: '江戸幕府', role: '技術奉行', stats: [61, 86, 33, 88], ideology: '佐幕 70 / 開国 86', trait: '技術・砲台', portrait: 'assets/portraits/egawa-hidetatsu.png', tint: '#9b3e2f' },
    { id: 'inoue-kaoru', name: '井上 馨', faction: '長州藩', role: '政治家', stats: [65, 58, 35, 94], ideology: '倒幕 82 / 開国 92', trait: '政治・経済', portrait: 'assets/portraits/inoue-kaoru.png', tint: '#4f6f58' },
    { id: 'abe-masahiro', name: '阿部 正弘', faction: '江戸幕府', role: '老中', stats: [58, 52, 30, 94], ideology: '佐幕 72 / 開国 78', trait: '政治・外交', portrait: 'assets/portraits/abe-masahiro.png', tint: '#9b3e2f' },
    { id: 'yamada-akiyoshi', name: '山田 顕義', faction: '長州藩', role: '軍事指揮官', stats: [78, 86, 70, 72], ideology: '倒幕 84 / 開国 70', trait: '軍事・軍制', portrait: 'assets/portraits/yamada-akiyoshi.png', tint: '#4f6f58' },
    { id: 'tatemi-naofumi', name: '立見 尚文', faction: '桑名藩', role: '軍事指揮官', stats: [91, 93, 82, 64], ideology: '佐幕 86 / 開国 62', trait: '軍事・精鋭', portrait: 'assets/portraits/tatemi-naofumi.png', tint: '#6b536d' },
    { id: 'otori-keisuke', name: '大鳥 圭介', faction: '旧幕府軍', role: '陸軍奉行', stats: [86, 91, 65, 76], ideology: '佐幕 88 / 開国 83', trait: '軍制改革・野戦', portrait: 'assets/portraits/otori-keisuke.png', tint: '#356784' },
    { id: 'ono-tomogoro', name: '小野 友五郎', faction: '幕府海軍', role: '航海士', stats: [72, 86, 42, 82], ideology: '佐幕 76 / 開国 90', trait: '海軍・航海', portrait: 'assets/portraits/ono-tomogoro.png', tint: '#356784' },
    { id: 'kurimoto-joun', name: '栗本 鋤雲', faction: '江戸幕府', role: '外交官', stats: [58, 55, 28, 91], ideology: '佐幕 72 / 開国 89', trait: '外交・蘭学', portrait: 'assets/portraits/kurimoto-joun.png', tint: '#9b3e2f' },
    { id: 'kusaka-genzui', name: '久坂 玄瑞', faction: '長州藩', role: '尊攘派志士', stats: [77, 73, 59, 82], ideology: '尊攘 95 / 開国 36', trait: '思想・軍事', portrait: 'assets/portraits/kusaka-genzui.png', tint: '#4f6f58' },
    { id: 'oyama-iwao', name: '大山 巌', faction: '薩摩藩', role: '砲兵指揮官', stats: [82, 88, 67, 71], ideology: '倒幕 80 / 開国 78', trait: '砲術・軍事', portrait: 'assets/portraits/oyama-iwao.png', tint: '#b78b37' },
    { id: 'godai-tomoatsu', name: '五代 友厚', faction: '薩摩藩', role: '商人・実業家', stats: [52, 58, 28, 93], ideology: '雄藩 / 開国 96', trait: '経済・殖産興業', portrait: 'assets/portraits/godai-tomoatsu.png', tint: '#b78b37' },
    { id: 'makino-tadayoshi', name: '牧野 忠恭', faction: '長岡藩', role: '藩主', stats: [59, 52, 29, 78], ideology: '佐幕 70 / 開国 68', trait: '藩政・調停', portrait: 'assets/portraits/makino-tadayoshi.png', tint: '#9e633d' },
    { id: 'makino-tadanori', name: '牧野 忠訓', faction: '長岡藩', role: '藩主・世子', stats: [62, 57, 33, 74], ideology: '佐幕 76 / 開国 64', trait: '藩政・継承', portrait: 'assets/portraits/makino-tadanori.png', tint: '#9e633d' },
    { id: 'yamamoto-taito', name: '山本 帯刀', faction: '長岡藩', role: '軍事指揮官', stats: [86, 83, 72, 61], ideology: '佐幕 88 / 開国 58', trait: '野戦・統率', portrait: 'assets/portraits/yamamoto-taito.png', tint: '#9e633d' },
    { id: 'mima-ichinoshin', name: '三間 市之進', faction: '長岡藩', role: '軍政家', stats: [74, 79, 45, 70], ideology: '佐幕 82 / 開国 66', trait: '作戦・兵站', portrait: 'assets/portraits/mima-ichinoshin.png', tint: '#9e633d' },
    { id: 'saigo-tanomo', name: '西郷 頼母', faction: '会津藩', role: '家老', stats: [73, 68, 37, 84], ideology: '佐幕 95 / 開国 42', trait: '政治・守城', portrait: 'assets/portraits/saigo-tanomo.png', tint: '#4a6687' },
    { id: 'tanaka-tosa', name: '田中 土佐', faction: '会津藩', role: '家老', stats: [64, 52, 28, 79], ideology: '佐幕 93 / 開国 36', trait: '藩政・調停', portrait: 'assets/portraits/tanaka-tosa.png', tint: '#4a6687' },
    { id: 'jinbo-kuranosuke', name: '神保 内蔵助', faction: '会津藩', role: '軍事奉行', stats: [79, 76, 54, 62], ideology: '佐幕 94 / 開国 38', trait: '防衛・統率', portrait: 'assets/portraits/jinbo-kuranosuke.png', tint: '#4a6687' },
    { id: 'akizuki-teijiro', name: '秋月 悌次郎', faction: '会津藩', role: '外交役', stats: [58, 50, 25, 90], ideology: '佐幕 83 / 開国 56', trait: '外交・情報', portrait: 'assets/portraits/akizuki-teijiro.png', tint: '#4a6687' },
    { id: 'sagawa-kanbei', name: '佐川 官兵衛', faction: '会津藩', role: '家臣・指揮官', stats: [91, 82, 95, 55], ideology: '佐幕 97 / 開国 29', trait: '武勇・突撃', portrait: 'assets/portraits/sagawa-kanbei.png', tint: '#4a6687' },
    { id: 'kajiwara-heima', name: '梶原 平馬', faction: '会津藩', role: '軍政家', stats: [70, 78, 42, 73], ideology: '佐幕 91 / 開国 40', trait: '作戦・兵站', portrait: 'assets/portraits/kajiwara-heima.png', tint: '#4a6687' }
  ],
  actions: [
    { id: 'reform', title: '軍制を改革する', text: '洋式調練を導入し、近代化を進める。', cost: 120, effect: { modernization: 8, tension: 2 }, log: '江戸で洋式調練が始まり、諸藩の視線が集まる。' },
    { id: 'court', title: '朝廷へ使者を送る', text: '公家への工作で正統性を求める。', cost: 80, effect: { court: 7, tension: -3 }, log: '京の政局に新たな使者が入った。' },
    { id: 'diplomacy', title: '列強と交渉する', text: '交易と技術導入を模索する。', cost: 100, effect: { modernization: 5, tension: 5 }, log: '横浜沖に外国艦が停泊し、交渉が始まった。' }
  ],
  events: [
    { year: 1853, month: 7, title: '黒船来航', text: '浦賀沖に異国船が現れた。幕府は開国か攘夷か、難しい決断を迫られる。', effect: { tension: 8 } },
    { year: 1854, month: 3, title: '日米和親条約', text: '開国の扉が開かれ、国内の思想対立がいっそう強まる。', effect: { court: -3, tension: 7 } },
    { year: 1860, month: 3, title: '桜田門外の変', text: '大老・井伊直弼が襲撃され、幕府の権威は大きく揺らいだ。', effect: { tension: 14, court: -6 } },
    { year: 1867, month: 10, title: '大政奉還', text: '政権返上をめぐり、新しい国家体制への道が開かれる。', effect: { tension: 10, court: 8 } },
    { year: 1868, month: 1, title: '鳥羽・伏見の戦い', text: '京で火蓋が切られた。日本を二分する内戦が始まる。', effect: { tension: 20 } }
  ]
};
