(() => {
  const $=s=>document.querySelector(s), saveKey='bakumatsu-fuunki-map-v1';
  const factions=[
    {id:'bakufu',name:'徳川幕府',color:'#d26045',doctrine:'佐幕・開国',capital:'江戸城',hanron:5,kyoto:35,start:{gold:2120,troops:24000,modern:22,prestige:54,people:67}},
    {id:'satsuma',name:'薩摩藩',color:'#e49d25',doctrine:'雄藩・現実派',capital:'鹿児島城',hanron:55,kyoto:20,start:{gold:1680,troops:11800,modern:35,prestige:44,people:65}},
    {id:'choshu',name:'長州藩',color:'#61a77a',doctrine:'攘夷・改革派',capital:'萩城',hanron:85,kyoto:15,start:{gold:1260,troops:9200,modern:30,prestige:41,people:52}},
    {id:'tosa',name:'土佐藩',color:'#9b6bcc',doctrine:'公議政体派',capital:'高知城',hanron:50,kyoto:20,start:{gold:970,troops:5900,modern:27,prestige:43,people:61}},
    {id:'saga',name:'佐賀藩',color:'#39a5aa',doctrine:'技術・開明派',capital:'佐賀城',hanron:40,kyoto:10,start:{gold:1380,troops:6900,modern:43,prestige:37,people:66}},
    {id:'mito',name:'水戸藩',color:'#699d56',doctrine:'尊王攘夷',capital:'水戸城',hanron:70,kyoto:25,start:{gold:920,troops:6700,modern:17,prestige:45,people:48}},
    {id:'aizu',name:'会津藩',color:'#7397c8',doctrine:'佐幕・京都守護',capital:'若松城',hanron:5,kyoto:30,start:{gold:1040,troops:7600,modern:24,prestige:40,people:73}},
    {id:'kuwana',name:'桑名藩',color:'#b36f9a',doctrine:'佐幕・精鋭',capital:'桑名城',hanron:10,kyoto:25,start:{gold:860,troops:5600,modern:25,prestige:35,people:68}},
    {id:'shonai',name:'庄内藩',color:'#9b8253',doctrine:'佐幕・北国',capital:'鶴岡城',hanron:15,kyoto:5,start:{gold:740,troops:5200,modern:18,prestige:32,people:71}},
    {id:'nagaoka',name:'長岡藩',color:'#c57145',doctrine:'中立・近代軍制',capital:'長岡城',hanron:35,kyoto:5,start:{gold:830,troops:4800,modern:36,prestige:34,people:64}},
    {id:'fukui',name:'福井藩',color:'#829bd0',doctrine:'公議政体・改革',capital:'福井城',hanron:45,kyoto:25,start:{gold:1110,troops:6100,modern:34,prestige:47,people:69}}
  ];
  const HANRON_BANDS=[
    {max:25,name:'佐幕',en:'Pro-Shogunate'},
    {max:50,name:'公武合体',en:'Kobu Gattai'},
    {max:75,name:'尊王攘夷',en:'Sonno Joi'},
    {max:101,name:'倒幕',en:'Anti-Shogunate'}
  ];
  const hanronBand=v=>HANRON_BANDS.find(b=>v<b.max)||HANRON_BANDS[HANRON_BANDS.length-1];
  const KYOTO_TIERS=[
    {max:20,name:'無位無官'},
    {max:40,name:'内々の伝手'},
    {max:60,name:'御用達'},
    {max:80,name:'朝議に列す'},
    {max:101,name:'朝議を主導'}
  ];
  const kyotoTier=v=>KYOTO_TIERS.find(t=>v<t.max)||KYOTO_TIERS[KYOTO_TIERS.length-1];
  const FOREIGN_TIERS=[
    {max:20,name:'独立独歩'},
    {max:40,name:'交易あり'},
    {max:60,name:'依存進行'},
    {max:80,name:'外国頼み'},
    {max:101,name:'半植民地化寸前'}
  ];
  const foreignTier=v=>FOREIGN_TIERS.find(t=>v<t.max)||FOREIGN_TIERS[FOREIGN_TIERS.length-1];
  const scenarios=[
    {id:'blackships',title:'黒船来航',year:1853,month:7,copy:'開国か攘夷か。幕末の幕が上がる。',players:['bakufu','satsuma','choshu','saga','mito','aizu','fukui']},
    {id:'ansei',title:'安政の政局',year:1858,month:6,copy:'条約、朝廷、藩内抗争。政局の綱引きが始まる。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','fukui']},
    {id:'kyoto',title:'京の政変',year:1863,month:8,copy:'京都の主導権を巡り、諸藩が武威と策を競う。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']},
    {id:'satcho',title:'薩長同盟',year:1866,month:3,copy:'密約は結ばれた。天下の帰趨は戦と外交に委ねられる。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']},
    {id:'taisei',title:'大政奉還',year:1867,month:10,copy:'戦わずして政権を返すか、武力で新時代を奪うか。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']},
    {id:'boshin',title:'戊辰戦争',year:1868,month:1,copy:'鳥羽・伏見の銃声が全国を戦火へ巻き込む。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']}
  ];
  const era={1853:'嘉永6',1854:'安政元',1855:'安政2',1856:'安政3',1857:'安政4',1858:'安政5',1859:'安政6',1860:'万延元',1861:'文久元',1862:'文久2',1863:'文久3',1864:'元治元',1865:'慶応元',1866:'慶応2',1867:'慶応3',1868:'明治元',1869:'明治2'};
  const DIFFICULTIES=[
    {id:'easy',name:'易しい',en:'Easy',copy:'国力に余裕を持ち、政局の荒波も緩やかに。初めての方向け。',startMul:1.25,badMul:0.7},
    {id:'normal',name:'普通',en:'Normal',copy:'史実に近い国力と厳しさで、幕末の政局を切り盛りする。',startMul:1,badMul:1},
    {id:'hard',name:'難しい',en:'Hard',copy:'乏しい国力のまま、民心の荒れも増す。上級者向け。',startMul:0.8,badMul:1.35}
  ];
  const state={scenario:'blackships',faction:null,difficulty:'normal',year:1853,month:7,turn:1,selected:'edo',gold:0,troops:0,modern:0,prestige:0,people:0,hanron:50,kyotoInfluence:0,kyotoTriumph:false,foreignDependency:0,foreignBacklash:false,blackshipsChoice:null,recruitedRyoma:false,treatyChoice:null,resistedTaisei:false,log:[],control:{},gameOver:false};
  const ACTION_SCENES={
    reform:{title:'軍制改革',image:'assets/bakumatsu/actions/reform.png',copy:'洋式調練と装備の標準化を進め、藩兵を近代的な軍制へ改めた。'},
    trade:{title:'港湾・交易',image:'assets/bakumatsu/actions/trade.png',copy:'港に商船と荷が集まり、交易の活気が藩の財政を潤した。'},
    retain:{title:'人材登用',image:'assets/bakumatsu/actions/retain.png',copy:'家柄だけにとらわれず、時勢を動かす才を藩政へ迎え入れた。'},
    radicalize:{title:'尊王攘夷を唱える',image:'assets/bakumatsu/actions/radicalize.png',copy:'尊王攘夷の大義を掲げ、若き藩士たちの熱を政局へ向けた。'},
    moderate:{title:'公武合体を推進する',image:'assets/bakumatsu/actions/moderate.png',copy:'朝廷と幕府の協調を説き、対立の激化を抑える道を選んだ。'},
    britishArms:{title:'英国から兵器を購入',image:'assets/bakumatsu/actions/british-arms.png',copy:'英国商人から洋式銃砲を買い入れ、藩兵の火力を大きく高めた。'},
    frenchAdvisors:{title:'仏国から軍制顧問を招く',image:'assets/bakumatsu/actions/french-advisors.png',copy:'仏国軍事顧問の教練を受け、隊列と指揮の近代化を進めた。'},
    march:{title:'示威行軍',image:'assets/bakumatsu/actions/march.png',copy:'街道へ軍勢を進め、近隣諸藩に当藩の兵威と覚悟を示した。'},
    drill:{title:'実戦訓練',image:'assets/bakumatsu/actions/drill.png',copy:'実弾と砲煙の中で訓練を重ね、藩兵の実戦対応力を鍛えた。'}
  };
  // 座標は元画像（1672 × 941）に対する百分率。表示領域の切り取り後ではない。
  // projectPoint() が CSS と同じ cover 変換（MAP_FOCUS の位置合わせ込み）を掛ける。
  // 値の正しさは node scripts/verify-bakumatsu-map.mjs が地図画像の陸判定で機械検査する。
  const regions=[
    {id:'ezo',name:'箱館',area:'蝦夷地',x:70.0,y:26.5,owner:'bakufu',asset:'箱館港',kind:'港',power:52,note:'北方の玄関口。海軍と外国船の影が交錯する。'},
    {id:'shonai',name:'鶴岡',area:'庄内',x:67.5,y:42.0,owner:'shonai',asset:'鶴岡城',kind:'城',power:50,note:'日本海に面する北国の藩。結束の強い藩士団を抱える。'},
    {id:'tohoku',name:'若松',area:'会津',x:66.5,y:50.5,owner:'aizu',asset:'鶴ヶ城',kind:'城',power:61,note:'奥羽の要衝。会津武士の忠節は京の秩序を支える。'},
    {id:'nagaoka',name:'長岡',area:'越後',x:57.5,y:51.5,owner:'nagaoka',asset:'長岡城',kind:'城',power:54,note:'近代兵器と機動戦に活路を見いだす雪国の雄藩。'},
    {id:'echigo',name:'新潟',area:'越後',x:60.5,y:46.5,owner:'bakufu',asset:'新潟港',kind:'港',power:48,note:'日本海交易の要。海路を制する者が情報を制する。'},
    {id:'fukui',name:'福井',area:'越前',x:46.5,y:57.5,owner:'fukui',asset:'福井城',kind:'城',power:53,note:'松平春嶽のもと、改革と公議政体を模索する。'},
    {id:'mito',name:'水戸',area:'常陸',x:72.0,y:58.0,owner:'mito',asset:'水戸城',kind:'城',power:50,note:'尊王攘夷の思想が、関東の政局を揺さぶる。'},
    {id:'edo',name:'江戸',area:'武蔵',x:64.0,y:63.0,owner:'bakufu',asset:'江戸城',kind:'城',power:85,note:'将軍家の本拠。全国の政局がここから動く。'},
    {id:'kyoto',name:'京都',area:'山城',x:43.5,y:62.5,owner:'neutral',asset:'京都御所',kind:'御所',power:72,note:'勅許と朝廷工作が、国家の正統性を左右する。'},
    {id:'kuwana',name:'桑名',area:'伊勢',x:50.5,y:66.0,owner:'kuwana',asset:'桑名城',kind:'城',power:48,note:'京畿に近い佐幕の要。精強な藩兵が幕府を支える。'},
    {id:'choshu',name:'萩',area:'長州',x:22.5,y:63.0,owner:'choshu',asset:'萩城下',kind:'城',power:59,note:'西国の雄藩。軍制改革の熱が藩内を走る。'},
    {id:'tosa',name:'高知',area:'土佐',x:28.5,y:75.5,owner:'tosa',asset:'高知城',kind:'城',power:47,note:'海援隊と志士たちが新しい国家像を語る。'},
    {id:'saga',name:'佐賀',area:'肥前',x:13.0,y:69.0,owner:'saga',asset:'佐賀城',kind:'城',power:56,note:'反射炉と精錬方を擁する、技術先進の雄藩。'},
    {id:'satsuma',name:'鹿児島',area:'薩摩',x:12.5,y:83.0,owner:'satsuma',asset:'鹿児島城下',kind:'城',power:67,note:'豊かな財政と対外交易を持つ西南の大藩。'}
  ];
  const events=[{y:1853,m:7,t:'黒船来航',d:'浦賀沖に異国船が現れた。幕末の嵐が始まる。',e:{people:-4,prestige:2}},{y:1854,m:3,t:'日米和親条約',d:'開国の扉が開かれ、国内の思想対立が強まる。',branch:()=>showTreatyChoice()},{y:1860,m:3,t:'桜田門外の変',d:'大老の横死により、幕府の権威は揺らいだ。',e:{prestige:-6,people:-9,hanron:6}},{y:1863,m:8,t:'八月十八日の政変',d:'京都の政局が大きく動く。',dynamic:()=>state.hanron>=50?{effect:{prestige:-8,people:-6,hanron:-4},text:'尊攘急進派として、御所からの締め出しを受けた。京の政局から遠ざけられる。'}:{effect:{prestige:10,people:2,hanron:-6},text:'会津・薩摩と結び、政変を主導した。京の実権を掌握する。'}},{y:1866,m:3,t:'薩長同盟',d:'西国の二藩が密約を結んだ。',e:{prestige:6,modern:4,hanron:10}},{y:1867,m:10,t:'大政奉還',d:'政権返上をめぐり、新時代への扉が開かれる。',branch:()=>showTaiseiChoice()},{y:1868,m:1,t:'鳥羽・伏見の戦い',d:'京で火蓋が切られ、内戦が始まった。',e:{troops:-1200,people:-12,hanron:8}}];
  const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n)); const faction=id=>factions.find(x=>x.id===id)||{name:'朝廷・中立',color:'#a5a5a5',doctrine:'朝廷領'}; const region=id=>regions.find(x=>x.id===id); const date=()=>`${era[state.year]}年 ${state.month}月・第${state.turn}月`; const difficulty=()=>DIFFICULTIES.find(d=>d.id===state.difficulty)||DIFFICULTIES[1];
  function log(text,type=''){state.log.unshift({text,type,stamp:`${era[state.year]} ${state.month}月`});state.log=state.log.slice(0,7)} function adjust(e){const bad=difficulty().badMul;Object.entries(e).forEach(([k,v])=>{if(v<0)v*=bad;if(k==='gold'||k==='troops')state[k]=Math.max(0,Math.round(state[k]+v));else state[k]=clamp(Math.round(state[k]+v))})}
  function owner(r){return state.control[r.id]||r.owner} function isMine(r){return owner(r)===state.faction} function current(){return faction(state.faction)}
  const chosenScenario=()=>scenarios.find(s=>s.id===state.scenario)||scenarios[0];
  function setup(id,diffId){const f=faction(id),s=chosenScenario(),years=s.year-1853,d=DIFFICULTIES.find(x=>x.id===diffId)||DIFFICULTIES[1];Object.assign(state,{faction:id,difficulty:d.id,year:s.year,month:s.month,turn:1,selected:id==='aizu'?'tohoku':id==='bakufu'?'edo':id,control:{},gameOver:false,gold:Math.round((f.start.gold+years*90)*d.startMul),troops:Math.round((f.start.troops+years*240)*d.startMul),modern:clamp(f.start.modern+years*2),prestige:clamp(f.start.prestige+years),people:f.start.people,hanron:f.hanron,kyotoInfluence:f.kyoto,kyotoTriumph:false,foreignDependency:0,foreignBacklash:false,blackshipsChoice:null,recruitedRyoma:false,treatyChoice:null,resistedTaisei:false,log:[]});log(`${s.title}。${s.copy}`,'event');log(`難易度「${d.name}」で開始した。`,'');$('#start-dialog').close();render();if(s.id==='blackships')showBlackshipsChoice()}
  function renderHud(){const f=current(),playing=Boolean(state.faction);document.documentElement.style.setProperty('--clan',f.color);$('#clan-mark').style.background=f.color;$('#faction-label').textContent=playing?f.name:'勢力を選択';$('#date-label').textContent=playing?date():'シナリオを選択してください';$('#treasury-label').textContent=playing?state.gold.toLocaleString():'—';$('#military-label').textContent=playing?(state.troops/10000).toFixed(1)+'千':'—';$('#modernization-label').textContent=playing?state.modern:'—';$('#influence-label').textContent=playing?state.prestige:'—';$('#stability-label').textContent=playing?state.people:'—';$('#hanron-label').textContent=playing?hanronBand(state.hanron).name:'—';$('#hanron-sub').textContent=playing?`(${state.hanron})`:''}
  const MAP_IMAGE={width:1672,height:941};
  // 地図の敷き方。bakumatsu.css の .strategic-map の background-size / position と
  // 必ず同じ値にすること（片方だけ直すと拠点だけが無言で地図から浮く）。
  // contain 固定: map-stage の縦横比は画面サイズで 0.9〜1.5 まで動くので、cover だと
  // 横が最大48%切り取られて九州（佐賀・鹿児島）が枠外へ出る。全拠点を必ず見せる方を採る。
  const MAP_FIT='contain', MAP_FOCUS={x:0.5,y:0.5};
  function projectPoint(point,map){const width=map.clientWidth,height=map.clientHeight,fit=MAP_FIT==='contain'?Math.min:Math.max,scale=fit(width/MAP_IMAGE.width,height/MAP_IMAGE.height),renderedWidth=MAP_IMAGE.width*scale,renderedHeight=MAP_IMAGE.height*scale;return{x:(width-renderedWidth)*MAP_FOCUS.x+(point.x/100)*renderedWidth,y:(height-renderedHeight)*MAP_FOCUS.y+(point.y/100)*renderedHeight}}
  function route(a,b,map){const start=projectPoint(a,map),end=projectPoint(b,map),dx=end.x-start.x,dy=end.y-start.y,len=Math.hypot(dx,dy);return `<i class="route" style="left:${start.x}px;top:${start.y}px;width:${len}px;transform:rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)"></i>`}
  function renderMap(){const map=$('#map');map.innerHTML=route(regions[0],regions[1],map)+route(regions[1],regions[2],map)+route(regions[2],regions[3],map)+route(regions[3],regions[4],map)+route(regions[4],regions[5],map)+route(regions[4],regions[6],map)+route(regions[5],regions[7],map);regions.forEach(r=>{const f=faction(owner(r)),point=projectPoint(r,map);const b=document.createElement('button');b.className='node '+(state.selected===r.id?'active':'');b.style.cssText=`left:${point.x}px;top:${point.y}px;--owner:${f.color}`;b.innerHTML=`<i></i><span>${r.name}<small class="port"> ${r.kind}</small></span>`;b.onclick=()=>{state.selected=r.id;render();};map.append(b)})}
  function renderLocation(){if(!state.faction){$('#location-panel').innerHTML='<p class="empty">勢力を選んでください。</p>';return}const r=region(state.selected),f=faction(owner(r)),mine=isMine(r),isKyoto=r.id==='kyoto',img=r.kind==='港'?'assets/battles/naval-battle.png':r.id==='tohoku'?'assets/battles/siege-battle.png':'assets/battles/field-battle.png';const kyotoNote=isKyoto?`<p class="side-note">朝廷への影響力: <b style="color:var(--gold)">${state.kyotoInfluence}</b>/100（${kyotoTier(state.kyotoInfluence).name}）</p>`:'';$('#location-panel').innerHTML=`<img class="side-image" src="${img}" alt="${r.name}"><h1 class="side-title">${r.name}</h1><div class="side-owner"><i style="--owner:${f.color}"></i>${f.name}　${r.area}</div><p class="side-note">${r.note}</p>${kyotoNote}<div class="command-row">${isKyoto?'<button data-command="kyoto" class="wide">朝廷工作</button>':''}<button data-command="${mine?'domestic':'negotiate'}">${mine?'内政':'交渉'}</button><button data-command="${mine?'march':'invade'}">${mine?'出陣':'侵攻'}</button></div>`;document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>openCommand(b.dataset.command))}
  function renderFactions(){$('#faction-list').innerHTML=factions.map(f=>{const holds=regions.filter(r=>owner(r)===f.id).length;return `<div class="faction-row" style="--color:${f.color}"><i></i><span>${f.name}</span><b>${holds}拠点</b></div>`}).join('')}
  function renderLog(){$('#chronicle-list').innerHTML=state.log.map(x=>`<li class="${x.type}"><time>${x.stamp}</time>${x.text}</li>`).join('')}
  function render(){renderHud();renderMap();renderLocation();renderFactions();renderLog()}
  function showActionScene(id,customTitle,customCopy){const scene=ACTION_SCENES[id],d=$('#command-dialog');if(!scene)return;d.classList.add('action-result-dialog');d.innerHTML=`<figure class="action-result"><img src="${scene.image}" alt="${customTitle||scene.title}" loading="eager"><figcaption><p>実行結果 / ACTION COMPLETE</p><h2>${customTitle||scene.title}</h2><span>${customCopy||scene.copy}</span></figcaption></figure><button class="dialog-close" id="dialog-close">地図へ戻る</button>`;if(!d.open)d.showModal();$('#dialog-close').onclick=()=>{d.close();d.classList.remove('action-result-dialog')}}
  function openCommand(type){const r=region(state.selected),f=faction(owner(r)),d=$('#command-dialog');d.classList.remove('action-result-dialog');let inner='';if(type==='domestic')inner=`<p>内政 / ${r.name}</p><h2>藩政を整える</h2><p>選んだ施策が、領内と幕末の政局を動かす。当藩の藩論: ${hanronBand(state.hanron).name}（${state.hanron}） ／ 外国依存度: ${foreignTier(state.foreignDependency).name}（${state.foreignDependency}）</p><div class="command-options"><button data-act="reform"><b>軍制改革　100両</b><small>近代化 +8 / 兵力 +600 / 民心 -2</small></button><button data-act="trade"><b>港湾・交易　60両</b><small>金 +180 / 近代化 +2 / 民心 -2</small></button><button data-act="retain"><b>人材登用　90両</b><small>登用する人物の能力に応じて兵力・威信が変動</small></button><button data-act="radicalize"><b>尊王攘夷を唱える　50両</b><small>藩論 +8（倒幕寄りに） / 威信 +3 / 民心 -2</small></button><button data-act="moderate"><b>公武合体を推進する　50両</b><small>藩論 -8（佐幕寄りに） / 民心 +3 / 威信 +1</small></button><button data-act="britishArms"><b>英国から兵器を購入　150両</b><small>兵力 +800 / 近代化 +6 / 藩論 +4 / 外国依存度 +10 / 民心 -3</small></button><button data-act="frenchAdvisors"><b>仏国から軍制顧問を招く　150両</b><small>近代化 +8 / 兵力 +400 / 藩論 -4 / 外国依存度 +10 / 民心 -3</small></button></div>`;else if(type==='kyoto')inner=`<p>朝廷工作 / 京都</p><h2>朝廷への影響力を築く</h2><p>現在の影響力: ${state.kyotoInfluence}/100（${kyotoTier(state.kyotoInfluence).name}）</p><div class="command-options"><button data-act="courtwork"><b>朝廷工作　80両</b><small>影響力 +10 / 威信 +2</small></button><button data-act="noble"><b>公家への接触　50両</b><small>影響力 +6 / 藩論 +3</small></button><button data-act="donate"><b>献金　120両</b><small>影響力 +14 / 民心 -3</small></button><button data-act="guard"><b>藩兵派遣（兵 400）</b><small>影響力 +8 / 威信 +3</small></button><button data-act="intel"><b>情報工作　60両</b><small>影響力 +5 / 威信 +1</small></button></div>`;else if(type==='negotiate')inner=`<p>外交 / ${r.name}</p><h2>${f.name}へ使者を送る</h2><p>一門・公家・商人を通じて、相手の態度を探る。</p><div class="command-options"><button data-act="diplomacy"><b>同盟を提案　70両</b><small>威信 +6 / 民心 +2</small></button><button data-act="spy"><b>内情を探る　40両</b><small>威信 +3 / 成功すれば侵攻に有利</small></button></div>`;else if(type==='march')inner=`<p>出陣 / ${r.name}</p><h2>軍勢を動かす</h2><p>周辺の政局に圧力をかけ、味方の威信を示す。</p><div class="command-options"><button data-act="march"><b>示威行軍</b><small>兵力 -300 / 威信 +4 / 民心 -1</small></button><button data-act="drill"><b>実戦訓練</b><small>金 -70 / 兵力 +800 / 近代化 +2</small></button></div>`;else inner=`<p>侵攻 / ${r.name}</p><h2>${r.name}の主導権を争う</h2><p>${f.name}の拠点「${r.asset}」へ軍を向ける。勝利すれば領域はあなたのものとなる。</p><div class="command-options"><button data-act="attack"><b>正面攻撃</b><small>兵力を頼みに攻める</small></button><button data-act="modernAttack"><b>洋式砲兵を投入</b><small>近代化を頼みに攻める</small></button><button data-act="scheme"><b>調略・内応</b><small>威信を頼みに攻める</small></button></div>`;d.innerHTML=inner+'<button class="dialog-close" id="dialog-close">閉じる</button>';d.showModal();$('#dialog-close').onclick=()=>d.close();d.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act))}
  function checkKyotoTriumph(){if(!state.kyotoTriumph&&state.kyotoInfluence>=80){state.kyotoTriumph=true;adjust({prestige:15});log('朝廷内で確固たる信を得た。もはや政局の帰趨は当藩の存念一つで動く。','event')}}
  function checkForeignBacklash(){if(!state.foreignBacklash&&state.foreignDependency>=60){state.foreignBacklash=true;adjust({people:-10,prestige:-4});log('「外国に国を売るつもりか！」外国依存を咎める攘夷派の反発が藩内に広がった。','event')}}
  function showRecruitCard(p,troops,prestige,isRyoma){const d=$('#command-dialog');d.innerHTML=`<div class="recruit-card"><img class="recruit-portrait" src="${p.portrait}" alt="${p.name}"><div><p>人材登用</p><h2>${p.name}</h2><p class="side-note">${p.role}　／　${p.faction}</p><p class="side-note">${p.trait}</p>${isRyoma?'<p class="side-note recruit-ryoma">交渉仲介の才により、威信にさらに+4のボーナス。</p>':''}<p class="side-note">兵力 +${troops}　／　威信 +${prestige}</p></div></div><button class="dialog-close" id="dialog-close">閉じる</button>`;$('#dialog-close').onclick=()=>d.close()}
  function act(id){const cost={reform:100,trade:60,retain:90,diplomacy:70,spy:40,drill:70,radicalize:50,moderate:50,courtwork:80,noble:50,donate:120,guard:0,intel:60,britishArms:150,frenchAdvisors:150}[id]||0;if(state.gold<cost){log('金が不足している。','');$('#command-dialog').close();render();return}state.gold-=cost;if(id==='reform'){adjust({modern:8,troops:600,people:-2});log('洋式調練を導入し、藩兵の装備を改めた。')}if(id==='trade'){adjust({gold:180,modern:2,people:-2});log('港の交易が活気づき、蔵に金が入った。')}if(id==='retain'){const p=GAME_DATA.people[(state.turn*7)%GAME_DATA.people.length],avg=Math.round(p.stats.reduce((a,b)=>a+b,0)/p.stats.length),bonusTroops=Math.round(avg*4),bonusPrestige=Math.max(2,Math.round(avg/12)),isRyoma=p.id==='sakamoto-ryoma';if(isRyoma)state.recruitedRyoma=true;adjust({prestige:bonusPrestige+(isRyoma?4:0),troops:bonusTroops});log(`${p.name}（${p.role}）を登用した。${p.trait}が勢力を支える。兵力+${bonusTroops} / 威信+${bonusPrestige}${isRyoma?'（交渉仲介の才でさらに+4）':''}`,'event');showRecruitCard(p,bonusTroops,bonusPrestige,isRyoma);render();return}if(id==='diplomacy'){adjust({prestige:6,people:2});log('使者を送り、諸藩との交渉を始めた。')}if(id==='spy'){adjust({prestige:3});log('密偵から領内の情勢が届いた。')}if(id==='march'){adjust({troops:-300,prestige:4,people:-1});log('軍勢を動かし、周辺の諸藩へ威勢を示した。')}if(id==='drill'){adjust({troops:800,modern:2});log('実戦訓練を行い、兵の練度を高めた。')}if(id==='radicalize'){adjust({hanron:8,prestige:3,people:-2});log(`藩論が「${hanronBand(state.hanron).name}」に傾いた。尊王攘夷を唱え、藩内の志士が沸き立つ。`,'event')}if(id==='moderate'){adjust({hanron:-8,people:3,prestige:1});log(`藩論が「${hanronBand(state.hanron).name}」に傾いた。公武合体を推し、藩内は落ち着きを取り戻す。`,'event')}if(id==='courtwork'){adjust({kyotoInfluence:10,prestige:2});log('禁裏に伝手を築き、朝廷工作を進めた。')}if(id==='noble'){adjust({kyotoInfluence:6,hanron:3});log('公家衆に接触し、尊王の機運を後押しした。')}if(id==='donate'){adjust({kyotoInfluence:14,people:-3});log('禁裏へ多額の献金を行った。')}if(id==='guard'){if(state.troops<400){log('兵力が不足している。','');$('#command-dialog').close();render();return}state.troops-=400;adjust({kyotoInfluence:8,prestige:3});log('藩兵を京へ派遣し、御所の警護にあたらせた。')}if(id==='intel'){adjust({kyotoInfluence:5,prestige:1});log('京の情勢を探り、諸藩の動きを把握した。')}if(id==='britishArms'){adjust({troops:800,modern:6,hanron:4,foreignDependency:10,people:-3});log('英国商人からアームストロング砲と小銃をあまた買い付けた。')}if(id==='frenchAdvisors'){adjust({modern:8,troops:400,hanron:-4,foreignDependency:10,people:-3});log('仏国軍事顧問団を招き、洋式軍制の指導を仰いだ。')}if(['courtwork','noble','donate','guard','intel'].includes(id))checkKyotoTriumph();if(['britishArms','frenchAdvisors'].includes(id))checkForeignBacklash();if(['attack','modernAttack','scheme'].includes(id))resolveAttack(id);$('#command-dialog').close();render()}
  function resolveAttack(kind){const r=region(state.selected),def=r.power+Math.floor(Math.random()*28),base=Math.round(state.troops/260)+state.modern/2+state.prestige/3;const bonus=kind==='modernAttack'?state.modern/2:kind==='scheme'?state.prestige/2:state.troops/520;const result=base+bonus+Math.floor(Math.random()*25);state.troops=Math.max(0,state.troops-650);if(result>=def){state.control[r.id]=state.faction;adjust({prestige:10,people:2});log(`${r.name}を攻略。${current().name}の勢力圏に加えた。`,'event')}else{adjust({people:-7,prestige:-3});log(`${r.name}への侵攻は失敗。軍勢は退いた。`,'') }}
  function eventEffectMultiplier(e){if(e.t==='桜田門外の変')return(state.blackshipsChoice==='resist'?1.4:0.7)*(state.treatyChoice==='push'?1.15:0.95);if(e.t==='鳥羽・伏見の戦い')return state.resistedTaisei?1.5:0.8;return 1}
  function next(){if(!state.faction||state.gameOver)return;state.month++;state.turn++;if(state.month===13){state.month=1;state.year++;adjust({gold:180,people:1})}const e=events.find(x=>x.y===state.year&&x.m===state.month);if(e&&e.branch){log(`${e.t} — ${e.d}`,'event');render();e.branch();return}if(e&&e.dynamic){const r=e.dynamic();adjust(r.effect);log(`${e.t} — ${r.text}`,'event')}else if(e){const mul=eventEffectMultiplier(e),scaled=mul===1?e.e:Object.fromEntries(Object.entries(e.e).map(([k,v])=>[k,Math.round(v*mul)])),ryomaBonus=(e.t==='薩長同盟'&&state.recruitedRyoma);if(ryomaBonus)Object.keys(scaled).forEach(k=>scaled[k]=Math.round(scaled[k]*1.5));adjust(scaled);log(`${e.t} — ${e.d}${ryomaBonus?'（坂本龍馬の仲介が実を結んだ）':''}`,'event')}else if(Math.random()>.64){adjust({people:-2});log('開国派と攘夷派の対立が、街道の空気を不穏にした。')}if(state.year>=1869||state.people<=0){state.gameOver=true;log(state.people<=0?'民心を失い、政権は瓦解した。':'激動の幕末を越え、新しい時代への礎を築いた。','event')}render()}
  function showEventChoice(cfg){const d=$('#command-dialog');d.innerHTML=`<p>${cfg.date}</p><h2>${cfg.title}</h2><p>${cfg.body}</p><div class="command-options">${cfg.options.map((o,i)=>`<button data-idx="${i}"><b>${o.label}</b><small>${o.desc}</small></button>`).join('')}</div>`;d.showModal();d.querySelectorAll('[data-idx]').forEach(b=>b.onclick=()=>{const o=cfg.options[+b.dataset.idx];adjust(o.effect);if(o.onPick)o.onPick();log(o.log,'event');d.close();render()})}
  function showBlackshipsChoice(){showEventChoice({date:'嘉永六年 六月',title:'黒船来航',body:'浦賀沖に異国船が現れた。幕府へ開国を迫っている。当藩はどう構えるか——この選択が、後の政局の火種の大きさを左右する。',options:[{label:'開国を受け入れる',desc:'近代化 +4 / 外国依存度 +8 / 藩論 -6（公武合体寄りに） / 威信 -3',effect:{modern:4,foreignDependency:8,hanron:-6,prestige:-3},onPick:()=>state.blackshipsChoice='open',log:'黒船の威容に押され、開国を受け入れた。近代化の道が開けたが、攘夷派の反発も燻る。'},{label:'攘夷を貫く',desc:'威信 +5 / 民心 +4 / 藩論 +10（尊王攘夷寄りに） / 近代化 -2',effect:{prestige:5,people:4,hanron:10,modern:-2},onPick:()=>state.blackshipsChoice='resist',log:'異国船を退け、祖法を守る構えを示した。志士たちは沸き立つが、列強との緊張は高まる。'}]})}
  function showTreatyChoice(){showEventChoice({date:`${era[state.year]}年 ${state.month}月`,title:'日米和親条約',body:'開国の扉が開かれた。通商条約への道をどこまで進めるか、国内の思想対立が強まっている。',options:[{label:'通商条約の締結を急ぐ',desc:'近代化 +6 / 外国依存度 +6 / 藩論 -4（公武合体寄りに） / 民心 -3',effect:{modern:6,foreignDependency:6,hanron:-4,people:-3},onPick:()=>state.treatyChoice='push',log:'通商条約の締結を急ぎ、開国路線を鮮明にした。攘夷派の反発は必至。'},{label:'開国を最小限にとどめる',desc:'藩論 +3（尊王攘夷寄りに） / 民心 +2 / 威信 -2',effect:{hanron:3,people:2,prestige:-2},onPick:()=>state.treatyChoice='hold',log:'開港を最小限にとどめ、国内の反発を和らげた。近代化は遅れる。'}]})}
  function showTaiseiChoice(){showEventChoice({date:`${era[state.year]}年 ${state.month}月`,title:'大政奉還',body:'政権返上をめぐり、新時代への扉が開かれようとしている。戦わずして政権を返すか、武力で新時代を奪うか。',options:[{label:'政権返上を支持する',desc:'威信 +10 / 藩論 -5（穏健寄りに） / 民心 +4',effect:{prestige:10,hanron:-5,people:4},onPick:()=>state.resistedTaisei=false,log:'大政奉還を支持し、新体制への道を開いた。'},{label:'徹底抗戦を叫ぶ',desc:'威信 +4 / 兵力 +500 / 藩論 +12（急進寄りに） / 民心 -2',effect:{prestige:4,troops:500,hanron:12,people:-2},onPick:()=>state.resistedTaisei=true,log:'大政奉還に抗い、徹底抗戦を叫んだ。旧幕府方の血気が高まる。'}]})}
  function persist(){localStorage.setItem(saveKey,JSON.stringify(state));log('政局を記録した。');render()}function restore(){try{const x=JSON.parse(localStorage.getItem(saveKey));if(x?.faction)Object.assign(state,x)}catch{}}
  function showStep(name){document.querySelectorAll('#start-dialog .step').forEach(el=>{el.hidden=el.dataset.step!==name});const dlg=$('#start-dialog');dlg.scrollTop=0}
  function renderScenarioChoices(){const s=chosenScenario();$('#scenario-title').textContent=`${era[s.year]}年・${s.title}`;$('#scenario-copy').textContent=s.copy;$('#scenario-choices').innerHTML=scenarios.map(x=>`<button class="scenario ${x.id===s.id?'active':''}" data-s="${x.id}"><strong>${era[x.year]} ${x.title}</strong><small>${x.players.length}勢力</small></button>`).join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{state.scenario=b.dataset.s;renderScenarioChoices();renderFactionChoices();showStep('faction')})}
  function renderFactionChoices(){const s=chosenScenario();$('#faction-copy').textContent=`${era[s.year]}年・${s.title} — ${s.players.length}勢力の中から選ぶ。`;$('#faction-choices').innerHTML=s.players.map(id=>{const f=faction(id);return `<button class="choice" data-f="${f.id}" style="border-left:4px solid ${f.color}"><strong>${f.name}</strong><small>${f.doctrine} / ${f.capital}</small></button>`}).join('');document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{state._pendingFaction=b.dataset.f;renderDifficultyChoices();showStep('difficulty')})}
  function renderDifficultyChoices(){$('#difficulty-choices').innerHTML=DIFFICULTIES.map(d=>`<button class="choice ${d.id===state.difficulty?'active':''}" data-d="${d.id}"><strong>${d.name}（${d.en}）</strong><small>${d.copy}</small></button>`).join('');document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>setup(state._pendingFaction,b.dataset.d))}
  function backToTitle(){localStorage.removeItem(saveKey);Object.assign(state,{scenario:'blackships',faction:null,difficulty:'normal',year:1853,month:7,turn:1,selected:'edo',gold:0,troops:0,modern:0,prestige:0,people:0,hanron:50,kyotoInfluence:0,kyotoTriumph:false,foreignDependency:0,foreignBacklash:false,blackshipsChoice:null,recruitedRyoma:false,treatyChoice:null,resistedTaisei:false,log:[],control:{},gameOver:false});state._pendingFaction=null;renderScenarioChoices();render();showStep('title');if(!$('#start-dialog').open)$('#start-dialog').showModal()}
  document.addEventListener('click',e=>{const button=e.target.closest('#command-dialog [data-act]'),id=button?.dataset.act;if(!ACTION_SCENES[id])return;const before=JSON.stringify([state.gold,state.troops,state.modern,state.prestige,state.people,state.hanron,state.foreignDependency,state.log[0]?.text]);setTimeout(()=>{const after=JSON.stringify([state.gold,state.troops,state.modern,state.prestige,state.people,state.hanron,state.foreignDependency,state.log[0]?.text]);if(before!==after)showActionScene(id)},0)},true);
  $('#advance-button').onclick=next;$('#save-button').onclick=persist;$('#reset-button').onclick=backToTitle;$('#title-start').onclick=()=>showStep('scenario');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>showStep(b.dataset.back));document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();next()}});let resizeFrame;addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(renderMap)});restore();renderScenarioChoices();render();if(!state.faction){showStep('title');$('#start-dialog').showModal()}
})();
