(() => {
  const $=s=>document.querySelector(s), saveKey='bakumatsu-fuunki-map-v1';
  const factions=[
    {id:'bakufu',name:'徳川幕府',color:'#d26045',doctrine:'佐幕・開国',capital:'江戸城',start:{gold:2120,troops:24000,modern:22,prestige:54,people:67}},
    {id:'satsuma',name:'薩摩藩',color:'#e49d25',doctrine:'雄藩・現実派',capital:'鹿児島城',start:{gold:1680,troops:11800,modern:35,prestige:44,people:65}},
    {id:'choshu',name:'長州藩',color:'#61a77a',doctrine:'攘夷・改革派',capital:'萩城',start:{gold:1260,troops:9200,modern:30,prestige:41,people:52}},
    {id:'tosa',name:'土佐藩',color:'#9b6bcc',doctrine:'公議政体派',capital:'高知城',start:{gold:970,troops:5900,modern:27,prestige:43,people:61}},
    {id:'saga',name:'佐賀藩',color:'#39a5aa',doctrine:'技術・開明派',capital:'佐賀城',start:{gold:1380,troops:6900,modern:43,prestige:37,people:66}},
    {id:'mito',name:'水戸藩',color:'#699d56',doctrine:'尊王攘夷',capital:'水戸城',start:{gold:920,troops:6700,modern:17,prestige:45,people:48}},
    {id:'aizu',name:'会津藩',color:'#7397c8',doctrine:'佐幕・京都守護',capital:'若松城',start:{gold:1040,troops:7600,modern:24,prestige:40,people:73}},
    {id:'kuwana',name:'桑名藩',color:'#b36f9a',doctrine:'佐幕・精鋭',capital:'桑名城',start:{gold:860,troops:5600,modern:25,prestige:35,people:68}},
    {id:'shonai',name:'庄内藩',color:'#9b8253',doctrine:'佐幕・北国',capital:'鶴岡城',start:{gold:740,troops:5200,modern:18,prestige:32,people:71}},
    {id:'nagaoka',name:'長岡藩',color:'#c57145',doctrine:'中立・近代軍制',capital:'長岡城',start:{gold:830,troops:4800,modern:36,prestige:34,people:64}},
    {id:'fukui',name:'福井藩',color:'#829bd0',doctrine:'公議政体・改革',capital:'福井城',start:{gold:1110,troops:6100,modern:34,prestige:47,people:69}}
  ];
  const scenarios=[
    {id:'blackships',title:'黒船来航',year:1853,month:7,copy:'開国か攘夷か。幕末の幕が上がる。',players:['bakufu','satsuma','choshu','saga','mito','aizu','fukui']},
    {id:'ansei',title:'安政の政局',year:1858,month:6,copy:'条約、朝廷、藩内抗争。政局の綱引きが始まる。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','fukui']},
    {id:'kyoto',title:'京の政変',year:1863,month:8,copy:'京都の主導権を巡り、諸藩が武威と策を競う。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']},
    {id:'satcho',title:'薩長同盟',year:1866,month:3,copy:'密約は結ばれた。天下の帰趨は戦と外交に委ねられる。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']},
    {id:'taisei',title:'大政奉還',year:1867,month:10,copy:'戦わずして政権を返すか、武力で新時代を奪うか。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']},
    {id:'boshin',title:'戊辰戦争',year:1868,month:1,copy:'鳥羽・伏見の銃声が全国を戦火へ巻き込む。',players:['bakufu','satsuma','choshu','saga','mito','aizu','kuwana','shonai','nagaoka','fukui','tosa']}
  ];
  const era={1853:'嘉永6',1854:'安政元',1855:'安政2',1856:'安政3',1857:'安政4',1858:'安政5',1859:'安政6',1860:'万延元',1861:'文久元',1862:'文久2',1863:'文久3',1864:'元治元',1865:'慶応元',1866:'慶応2',1867:'慶応3',1868:'明治元',1869:'明治2'};
  const state={scenario:'blackships',faction:null,year:1853,month:7,turn:1,selected:'edo',gold:0,troops:0,modern:0,prestige:0,people:0,log:[],control:{},gameOver:false};
  // Coordinates are percentages of the source map image (1672 × 941), not the
  // cropped viewport. projectPoint() applies the same cover transform as CSS.
  const regions=[
    {id:'ezo',name:'箱館',area:'蝦夷地',x:76.3,y:27.0,owner:'bakufu',asset:'箱館港',kind:'港',power:52,note:'北方の玄関口。海軍と外国船の影が交錯する。'},
    {id:'shonai',name:'鶴岡',area:'庄内',x:60.7,y:38.5,owner:'shonai',asset:'鶴岡城',kind:'城',power:50,note:'日本海に面する北国の藩。結束の強い藩士団を抱える。'},
    {id:'tohoku',name:'若松',area:'会津',x:64.0,y:45.5,owner:'aizu',asset:'鶴ヶ城',kind:'城',power:61,note:'奥羽の要衝。会津武士の忠節は京の秩序を支える。'},
    {id:'nagaoka',name:'長岡',area:'越後',x:58.0,y:48.5,owner:'nagaoka',asset:'長岡城',kind:'城',power:54,note:'近代兵器と機動戦に活路を見いだす雪国の雄藩。'},
    {id:'echigo',name:'新潟',area:'越後',x:60.0,y:44.5,owner:'bakufu',asset:'新潟港',kind:'港',power:48,note:'日本海交易の要。海路を制する者が情報を制する。'},
    {id:'fukui',name:'福井',area:'越前',x:47.0,y:56.0,owner:'fukui',asset:'福井城',kind:'城',power:53,note:'松平春嶽のもと、改革と公議政体を模索する。'},
    {id:'mito',name:'水戸',area:'常陸',x:67.5,y:49.0,owner:'mito',asset:'水戸城',kind:'城',power:50,note:'尊王攘夷の思想が、関東の政局を揺さぶる。'},
    {id:'edo',name:'江戸',area:'武蔵',x:64.5,y:55.5,owner:'bakufu',asset:'江戸城',kind:'城',power:85,note:'将軍家の本拠。全国の政局がここから動く。'},
    {id:'kyoto',name:'京都',area:'山城',x:45.5,y:61.0,owner:'neutral',asset:'京都御所',kind:'御所',power:72,note:'勅許と朝廷工作が、国家の正統性を左右する。'},
    {id:'kuwana',name:'桑名',area:'伊勢',x:50.5,y:59.5,owner:'kuwana',asset:'桑名城',kind:'城',power:48,note:'京畿に近い佐幕の要。精強な藩兵が幕府を支える。'},
    {id:'choshu',name:'萩',area:'長州',x:31.5,y:62.5,owner:'choshu',asset:'萩城下',kind:'城',power:59,note:'西国の雄藩。軍制改革の熱が藩内を走る。'},
    {id:'tosa',name:'高知',area:'土佐',x:35.0,y:76.5,owner:'tosa',asset:'高知城',kind:'城',power:47,note:'海援隊と志士たちが新しい国家像を語る。'},
    {id:'saga',name:'佐賀',area:'肥前',x:20.0,y:69.5,owner:'saga',asset:'佐賀城',kind:'城',power:56,note:'反射炉と精錬方を擁する、技術先進の雄藩。'},
    {id:'satsuma',name:'鹿児島',area:'薩摩',x:18.0,y:83.0,owner:'satsuma',asset:'鹿児島城下',kind:'城',power:67,note:'豊かな財政と対外交易を持つ西南の大藩。'}
  ];
  const events=[{y:1853,m:7,t:'黒船来航',d:'浦賀沖に異国船が現れた。幕末の嵐が始まる。',e:{people:-4,prestige:2}},{y:1854,m:3,t:'日米和親条約',d:'開国の扉が開かれ、国内の思想対立が強まる。',e:{modern:3,people:-5}},{y:1860,m:3,t:'桜田門外の変',d:'大老の横死により、幕府の権威は揺らいだ。',e:{prestige:-6,people:-9}},{y:1863,m:8,t:'八月十八日の政変',d:'京都の政局が大きく動く。',e:{prestige:6,people:-3}},{y:1866,m:3,t:'薩長同盟',d:'西国の二藩が密約を結んだ。',e:{prestige:6,modern:4}},{y:1867,m:10,t:'大政奉還',d:'政権返上をめぐり、新時代への扉が開かれる。',e:{prestige:8,people:-3}},{y:1868,m:1,t:'鳥羽・伏見の戦い',d:'京で火蓋が切られ、内戦が始まった。',e:{troops:-1200,people:-12}}];
  const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n)); const faction=id=>factions.find(x=>x.id===id)||{name:'朝廷・中立',color:'#a5a5a5',doctrine:'朝廷領'}; const region=id=>regions.find(x=>x.id===id); const date=()=>`${era[state.year]}年 ${state.month}月・第${state.turn}月`;
  function log(text,type=''){state.log.unshift({text,type,stamp:`${era[state.year]} ${state.month}月`});state.log=state.log.slice(0,7)} function adjust(e){Object.entries(e).forEach(([k,v])=>{if(k==='gold'||k==='troops')state[k]=Math.max(0,state[k]+v);else state[k]=clamp(state[k]+v)})}
  function owner(r){return state.control[r.id]||r.owner} function isMine(r){return owner(r)===state.faction} function current(){return faction(state.faction)}
  const chosenScenario=()=>scenarios.find(s=>s.id===state.scenario)||scenarios[0];
  function setup(id){const f=faction(id),s=chosenScenario(),years=s.year-1853;Object.assign(state,{faction:id,year:s.year,month:s.month,turn:1,selected:id==='aizu'?'tohoku':id==='bakufu'?'edo':id,control:{},gameOver:false,gold:f.start.gold+years*90,troops:f.start.troops+years*240,modern:clamp(f.start.modern+years*2),prestige:clamp(f.start.prestige+years),people:f.start.people,log:[]});log(`${s.title}。${s.copy}`,'event');$('#start-dialog').close();render()}
  function renderHud(){const f=current(),playing=Boolean(state.faction);document.documentElement.style.setProperty('--clan',f.color);$('#clan-mark').style.background=f.color;$('#faction-label').textContent=playing?f.name:'勢力を選択';$('#date-label').textContent=playing?date():'シナリオを選択してください';$('#treasury-label').textContent=playing?state.gold.toLocaleString():'—';$('#military-label').textContent=playing?(state.troops/10000).toFixed(1)+'千':'—';$('#modernization-label').textContent=playing?state.modern:'—';$('#influence-label').textContent=playing?state.prestige:'—';$('#stability-label').textContent=playing?state.people:'—'}
  const MAP_IMAGE={width:1672,height:941};
  function projectPoint(point,map){const width=map.clientWidth,height=map.clientHeight,scale=Math.max(width/MAP_IMAGE.width,height/MAP_IMAGE.height),renderedWidth=MAP_IMAGE.width*scale,renderedHeight=MAP_IMAGE.height*scale;return{x:(width-renderedWidth)/2+(point.x/100)*renderedWidth,y:(height-renderedHeight)/2+(point.y/100)*renderedHeight}}
  function route(a,b,map){const start=projectPoint(a,map),end=projectPoint(b,map),dx=end.x-start.x,dy=end.y-start.y,len=Math.hypot(dx,dy);return `<i class="route" style="left:${start.x}px;top:${start.y}px;width:${len}px;transform:rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)"></i>`}
  function renderMap(){const map=$('#map');map.innerHTML=route(regions[0],regions[1],map)+route(regions[1],regions[2],map)+route(regions[2],regions[3],map)+route(regions[3],regions[4],map)+route(regions[4],regions[5],map)+route(regions[4],regions[6],map)+route(regions[5],regions[7],map);regions.forEach(r=>{const f=faction(owner(r)),point=projectPoint(r,map);const b=document.createElement('button');b.className='node '+(state.selected===r.id?'active':'');b.style.cssText=`left:${point.x}px;top:${point.y}px;--owner:${f.color}`;b.innerHTML=`<i></i><span>${r.name}<small class="port"> ${r.kind}</small></span>`;b.onclick=()=>{state.selected=r.id;render();};map.append(b)})}
  function renderLocation(){if(!state.faction){$('#location-panel').innerHTML='<p class="empty">勢力を選んでください。</p>';return}const r=region(state.selected),f=faction(owner(r)),mine=isMine(r),img=r.kind==='港'?'assets/battles/naval-battle.png':r.id==='tohoku'?'assets/battles/siege-battle.png':'assets/battles/field-battle.png';$('#location-panel').innerHTML=`<img class="side-image" src="${img}" alt="${r.name}"><h1 class="side-title">${r.name}</h1><div class="side-owner"><i style="--owner:${f.color}"></i>${f.name}　${r.area}</div><p class="side-note">${r.note}</p><div class="command-row"><button data-command="${mine?'domestic':'negotiate'}">${mine?'内政':'交渉'}</button><button data-command="${mine?'march':'invade'}">${mine?'出陣':'侵攻'}</button></div>`;document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>openCommand(b.dataset.command))}
  function renderFactions(){$('#faction-list').innerHTML=factions.map(f=>{const holds=regions.filter(r=>owner(r)===f.id).length;return `<div class="faction-row" style="--color:${f.color}"><i></i><span>${f.name}</span><b>${holds}拠点</b></div>`}).join('')}
  function renderLog(){$('#chronicle-list').innerHTML=state.log.map(x=>`<li class="${x.type}"><time>${x.stamp}</time>${x.text}</li>`).join('')}
  function render(){renderHud();renderMap();renderLocation();renderFactions();renderLog()}
  function openCommand(type){const r=region(state.selected),f=faction(owner(r)),d=$('#command-dialog');let inner='';if(type==='domestic')inner=`<p>内政 / ${r.name}</p><h2>藩政を整える</h2><p>選んだ施策が、領内と幕末の政局を動かす。</p><div class="command-options"><button data-act="reform"><b>軍制改革　100両</b><small>近代化 +8 / 兵力 +600 / 民心 -2</small></button><button data-act="trade"><b>港湾・交易　60両</b><small>金 +180 / 近代化 +2 / 民心 -2</small></button><button data-act="retain"><b>人材登用　90両</b><small>威信 +6 / 兵力 +300</small></button></div>`;else if(type==='negotiate')inner=`<p>外交 / ${r.name}</p><h2>${f.name}へ使者を送る</h2><p>一門・公家・商人を通じて、相手の態度を探る。</p><div class="command-options"><button data-act="diplomacy"><b>同盟を提案　70両</b><small>威信 +6 / 民心 +2</small></button><button data-act="spy"><b>内情を探る　40両</b><small>威信 +3 / 成功すれば侵攻に有利</small></button></div>`;else if(type==='march')inner=`<p>出陣 / ${r.name}</p><h2>軍勢を動かす</h2><p>周辺の政局に圧力をかけ、味方の威信を示す。</p><div class="command-options"><button data-act="march"><b>示威行軍</b><small>兵力 -300 / 威信 +4 / 民心 -1</small></button><button data-act="drill"><b>実戦訓練</b><small>金 -70 / 兵力 +800 / 近代化 +2</small></button></div>`;else inner=`<p>侵攻 / ${r.name}</p><h2>${r.name}の主導権を争う</h2><p>${f.name}の拠点「${r.asset}」へ軍を向ける。勝利すれば領域はあなたのものとなる。</p><div class="command-options"><button data-act="attack"><b>正面攻撃</b><small>兵力を頼みに攻める</small></button><button data-act="modernAttack"><b>洋式砲兵を投入</b><small>近代化を頼みに攻める</small></button><button data-act="scheme"><b>調略・内応</b><small>威信を頼みに攻める</small></button></div>`;d.innerHTML=inner+'<button class="dialog-close" id="dialog-close">閉じる</button>';d.showModal();$('#dialog-close').onclick=()=>d.close();d.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act))}
  function act(id){const cost={reform:100,trade:60,retain:90,diplomacy:70,spy:40,drill:70}[id]||0;if(state.gold<cost){log('金が不足している。','');$('#command-dialog').close();render();return}state.gold-=cost;if(id==='reform'){adjust({modern:8,troops:600,people:-2});log('洋式調練を導入し、藩兵の装備を改めた。')}if(id==='trade'){adjust({gold:180,modern:2,people:-2});log('港の交易が活気づき、蔵に金が入った。')}if(id==='retain'){adjust({prestige:6,troops:300});const p=GAME_DATA.people[(state.turn*7)%GAME_DATA.people.length];log(`${p.name}を登用した。${p.trait}が勢力を支える。`,'event')}if(id==='diplomacy'){adjust({prestige:6,people:2});log('使者を送り、諸藩との交渉を始めた。')}if(id==='spy'){adjust({prestige:3});log('密偵から領内の情勢が届いた。')}if(id==='march'){adjust({troops:-300,prestige:4,people:-1});log('軍勢を動かし、周辺の諸藩へ威勢を示した。')}if(id==='drill'){adjust({troops:800,modern:2});log('実戦訓練を行い、兵の練度を高めた。')}if(['attack','modernAttack','scheme'].includes(id))resolveAttack(id);$('#command-dialog').close();render()}
  function resolveAttack(kind){const r=region(state.selected),def=r.power+Math.floor(Math.random()*28),base=Math.round(state.troops/260)+state.modern/2+state.prestige/3;const bonus=kind==='modernAttack'?state.modern/2:kind==='scheme'?state.prestige/2:state.troops/520;const result=base+bonus+Math.floor(Math.random()*25);state.troops=Math.max(0,state.troops-650);if(result>=def){state.control[r.id]=state.faction;adjust({prestige:10,people:2});log(`${r.name}を攻略。${current().name}の勢力圏に加えた。`,'event')}else{adjust({people:-7,prestige:-3});log(`${r.name}への侵攻は失敗。軍勢は退いた。`,'') }}
  function next(){if(!state.faction||state.gameOver)return;state.month++;state.turn++;if(state.month===13){state.month=1;state.year++;adjust({gold:180,people:1})}const e=events.find(x=>x.y===state.year&&x.m===state.month);if(e){adjust(e.e);log(`${e.t} — ${e.d}`,'event')}else if(Math.random()>.64){adjust({people:-2});log('開国派と攘夷派の対立が、街道の空気を不穏にした。')}if(state.year>=1869||state.people<=0){state.gameOver=true;log(state.people<=0?'民心を失い、政権は瓦解した。':'激動の幕末を越え、新しい時代への礎を築いた。','event')}render()}
  function persist(){localStorage.setItem(saveKey,JSON.stringify(state));log('政局を記録した。');render()}function restore(){try{const x=JSON.parse(localStorage.getItem(saveKey));if(x?.faction)Object.assign(state,x)}catch{}}
  function renderScenarioChoices(){const s=chosenScenario();$('#scenario-title').textContent=`${era[s.year]}年・${s.title}`;$('#scenario-copy').textContent=s.copy;$('#scenario-choices').innerHTML=scenarios.map(x=>`<button class="scenario ${x.id===s.id?'active':''}" data-s="${x.id}"><strong>${era[x.year]} ${x.title}</strong><small>${x.players.length}勢力</small></button>`).join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{state.scenario=b.dataset.s;renderScenarioChoices()});$('#faction-choices').innerHTML=s.players.map(id=>{const f=faction(id);return `<button class="choice" data-f="${f.id}" style="border-left:4px solid ${f.color}"><strong>${f.name}</strong><small>${f.doctrine} / ${f.capital}</small></button>`}).join('');document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>setup(b.dataset.f))}
  function backToTitle(){localStorage.removeItem(saveKey);Object.assign(state,{scenario:'blackships',faction:null,year:1853,month:7,turn:1,selected:'edo',gold:0,troops:0,modern:0,prestige:0,people:0,log:[],control:{},gameOver:false});renderScenarioChoices();render();if(!$('#start-dialog').open)$('#start-dialog').showModal()}
  $('#advance-button').onclick=next;$('#save-button').onclick=persist;$('#reset-button').onclick=backToTitle;document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();next()}});let resizeFrame;addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(renderMap)});restore();renderScenarioChoices();render();if(!state.faction)$('#start-dialog').showModal()
})();
