-- ============================================================
-- hide portfolio - Supabase セットアップSQL
-- Supabase の SQL Editor に貼り付けて実行してください
-- ============================================================

-- 1. テーブル作成
-- ============================================================

-- ブログ記事
CREATE TABLE IF NOT EXISTS posts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  excerpt     TEXT,
  content     TEXT,
  tags        TEXT[] DEFAULT '{}',
  emoji       TEXT DEFAULT '📝',
  published   BOOLEAN DEFAULT false,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

-- 訪問者ログ
CREATE TABLE IF NOT EXISTS visits (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page       TEXT NOT NULL DEFAULT '/',
  referrer   TEXT,
  ua_hash    TEXT,
  visited_at TIMESTAMPTZ DEFAULT now()
);

-- お問い合わせ
CREATE TABLE IF NOT EXISTS contacts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL,
  message    TEXT NOT NULL CHECK (char_length(message) <= 2000),
  read       BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. RLS (Row Level Security) 有効化
-- ============================================================
ALTER TABLE posts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE visits   ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- 3. RLS ポリシー設定
-- ============================================================

-- posts: 匿名は公開記事のみ閲覧、認証済みは全操作
CREATE POLICY "公開記事は誰でも閲覧可" ON posts
  FOR SELECT TO anon USING (published = true);

CREATE POLICY "管理者は全操作可" ON posts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- visits: 誰でも挿入可、認証済みは閲覧可
CREATE POLICY "訪問ログは誰でも記録可" ON visits
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "管理者は訪問ログ閲覧可" ON visits
  FOR SELECT TO authenticated USING (true);

-- contacts: 誰でも送信可、認証済みは全操作可
CREATE POLICY "お問い合わせは誰でも送信可" ON contacts
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "管理者はお問い合わせ全操作可" ON contacts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. updated_at 自動更新トリガー
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 5. 日別訪問者数ビュー（ダッシュボード用）
-- ============================================================
CREATE OR REPLACE VIEW public_visit_stats AS
  SELECT
    DATE(visited_at) AS visit_date,
    COUNT(*) AS total_visits,
    COUNT(DISTINCT ua_hash) AS unique_visitors
  FROM visits
  GROUP BY DATE(visited_at)
  ORDER BY visit_date DESC;

GRANT SELECT ON public_visit_stats TO anon, authenticated;

-- 6. 初期データ: posts.json の記事を移行
-- ============================================================
INSERT INTO posts (title, excerpt, tags, emoji, published, created_at) VALUES
(
  'Canvas APIだけでゼルダ風ゲームを作った話',
  '外部ライブラリゼロ、Pure JavaScriptのCanvas APIだけでトップビューアクションRPGを実装した。タイルマップ設計からスプライト描画、衝突判定まで全部自前で作った記録。',
  ARRAY['JavaScript', 'Canvas API', 'Game Dev'],
  '⚔️',
  true,
  '2025-04-01 00:00:00+00'
),
(
  '将棋盤で妖怪バトル — Shogi RPGの設計思想',
  '9×9の将棋盤をRPGのフィールドに見立て、妖怪たちとパズル的なバトルをするゲームをReactで実装した。状態管理とSVGアニメーションの設計について。',
  ARRAY['React', 'SVG', 'Game Dev', '将棋'],
  '♟️',
  true,
  '2025-03-15 00:00:00+00'
),
(
  'パーティクルネットワーク背景をCanvas APIで実装する',
  '120個のパーティクルが近くにいると線で繋がり、マウス追随のグロー効果も加えたインタラクティブ背景の実装方法を解説。このポートフォリオの背景そのもの。',
  ARRAY['JavaScript', 'Canvas API', 'アニメーション'],
  '✨',
  true,
  '2025-02-20 00:00:00+00'
),
(
  'CSSだけで作るサイバーパンク風UIデザイン',
  'CSS変数・グラジェント・backdrop-filterを駆使したダークネオン系UIの構築テクニック。グリッチエフェクトやグロウシャドウもCSSアニメーションで実現。',
  ARRAY['CSS', 'UI Design', 'アニメーション'],
  '🎨',
  true,
  '2025-01-30 00:00:00+00'
);
