const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const formats=require('../assets/nes/formats.js');
function nes(){const b=new Uint8Array(16+16384+8192);b.set([78,69,83,26,1,1]);return b;}
function fds(sides=1,header=true){const b=new Uint8Array(sides*65500+(header?16:0));if(header)b.set([70,68,83,26,sides]);for(let i=0;i<sides;i++)b.set([1,...Array.from('*NINTENDO-HVC*',x=>x.charCodeAt(0))],(header?16:0)+i*65500);return b;}
test('iNES: header, mapper, trainer, battery and truncated body',()=>{let b=nes();b[6]=0x32;b[7]=0x40;assert.equal(formats.parse(b).mapper,67);assert.equal(formats.parse(b).battery,true);assert.throws(()=>formats.parse(b.slice(0,100)));b=new Uint8Array(16+512+16384);b.set([78,69,83,26,1,0,4]);assert.equal(formats.parse(b).prg,16384);});
test('NES 2.0: extended mapper, submapper, region and exponent encoding',()=>{const b=nes();b[7]=0x28;b[6]=0xc0;b[8]=0x51;b[12]=3;const info=formats.parse(b);assert.equal(info.mapper,300);assert.equal(info.submapper,5);assert.equal(info.region,'Dendy');const exponent=new Uint8Array(16+16384);exponent.set([78,69,83,26,56,0,0,8,0,15]);assert.equal(formats.parse(exponent).prg,16384);});
test('FDS: header/raw and all sides are checked',()=>{assert.equal(formats.parse(fds(2)).sides,2);assert.equal(formats.parse(fds(2,false)).sides,2);const b=fds(2);b[4]=1;assert.throws(()=>formats.parse(b));const corrupt=fds(2);corrupt[16+65500]=0;assert.throws(()=>formats.parse(corrupt));assert.throws(()=>formats.parse(new Uint8Array(65500)));assert.throws(()=>formats.parse(fds().slice(0,-1)));});
test('UNIF: structured chunks and bounds',()=>{const chunks=[];for(const [name,data] of [['MAPR',Buffer.from('NES-NROM\0')],['PRG0',Buffer.alloc(16384)]]){const head=Buffer.alloc(8);head.write(name);head.writeUInt32LE(data.length,4);chunks.push(head,data);}const h=Buffer.alloc(32);h.write('UNIF');const b=new Uint8Array(Buffer.concat([h,...chunks]));assert.equal(formats.parse(b).mapper,'NES-NROM');assert.throws(()=>formats.parse(b.slice(0,-1)));});
test('Unknown files and BIOS of wrong size are rejected',()=>{assert.throws(()=>formats.parse(new Uint8Array(100)));assert.throws(()=>formats.parse(new Uint8Array(8)));assert.throws(()=>formats.validateBios(new Uint8Array(8191)));assert.equal(formats.validateBios(new Uint8Array(8192)),true);});
test('Player boots pinned core, maps BIOS to disksys.rom and filters bridge input',()=>{
 const listeners={},messages=[],scripts=[],calls=[];const parent={postMessage:d=>messages.push(d)};const window={};let url=0;
 const ctx=vm.createContext({window,parent,location:{origin:'https://example.test'},File,URL:{createObjectURL:()=>`blob:test/${++url}`,revokeObjectURL:()=>{}},document:{createElement:()=>({}),body:{append:s=>scripts.push(s)},getElementById:()=>({replaceChildren:()=>{}})},addEventListener:(k,f)=>listeners[k]=f});
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/nes/player.js'),'utf8'),ctx);
 const message=(data,origin='https://example.test',source=parent)=>listeners.message({origin,source,data});
 assert.equal(messages[0].type,'host-ready');message({type:'boot',session:10,rom:new File([nes()],'test.nes'),bios:new File([new Uint8Array(8192)],'disksys.rom'),core:'fceumm'},'https://attacker.test');assert.equal(scripts.length,0);
 message({type:'boot',session:10,rom:new File([nes()],'test.nes'),bios:new File([new Uint8Array(8192)],'disksys.rom'),core:'fceumm'});
 assert.equal(scripts[0].src,'https://cdn.emulatorjs.org/4.2.3/data/loader.js');assert.equal(window.EJS_core,'fceumm');assert.equal(window.EJS_gameName,'test.nes');assert.equal(window.EJS_threads,false);assert.ok(window.EJS_externalFiles['/disksys.rom']);
 window.EJS_emulator={gameManager:{getDiskCount:()=>2,simulateInput:(...a)=>calls.push(a),setCurrentDisk:i=>calls.push(['disk',i]),restart:()=>calls.push(['reset'])},pause:()=>calls.push(['pause']),play:()=>calls.push(['play'])};window.EJS_onGameStart();assert.equal(messages.at(-1).diskCount,2);
 message({type:'input',session:10,button:8,value:1});assert.deepEqual(calls.at(-1),[0,8,1]);message({type:'input',session:9,button:0,value:1});assert.equal(calls.length,1);message({type:'disk',session:10,index:2});assert.equal(calls.length,1);message({type:'disk',session:10,index:1});assert.deepEqual(calls.at(-1),['disk',1]);message({type:'pause',session:10,paused:true});assert.deepEqual(calls.at(-1),['pause']);
});
